insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('848-76-7247', 'Room 1546', 'Rusty');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('634-02-5146', 'Room 768', 'Finlay');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('808-59-1906', 'Suite 79', 'Giacobo');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('207-83-8823', 'PO Box 61729', 'Mariel');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('120-08-9255', '15th Floor', 'Kellen');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('800-74-6056', 'Suite 46', 'Sheelah');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('524-45-3750', 'PO Box 1744', 'Thea');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('662-41-6672', 'Suite 87', 'Raquela');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('491-10-4131', 'Apt 937', 'Ealasaid');
insert into Cliente (cpf_Cliente, endereço, nome_cliente, placa_veiculo) values ('139-17-5596', 'Suite 73', 'Rusty');
