insert into Pecas (custo_peca, nome_peca) values (955.14, 'Marinated Artichokes');
insert into Pecas (custo_peca, nome_peca) values (404.59, 'Savory Oatmeal Cups');
insert into Pecas (custo_peca, nome_peca) values (678.06, 'Pumpkin Spice Creamer');
insert into Pecas (custo_peca, nome_peca) values (789.73, 'Mixed Nuts');
insert into Pecas (custo_peca, nome_peca) values (213.38, 'Dog Waste Bag Dispenser');
insert into Pecas (custo_peca, nome_peca) values (919.81, 'Thai Peanut Dressing');
insert into Pecas (custo_peca, nome_peca) values (556.96, 'Creamy Spinach Dip');
insert into Pecas (custo_peca, nome_peca) values (245.75, 'Classic Bagels');
insert into Pecas (custo_peca, nome_peca) values (240.86, 'Repair Tool Set for Home Improvement');
insert into Pecas (custo_peca, nome_peca) values (825.08, 'Chocolate Chip Muffins');
insert into Pecas (custo_peca, nome_peca) values (187.33, 'Whole Wheat Bread');
insert into Pecas (custo_peca, nome_peca) values (916.99, 'Almond Quinoa Salad');
insert into Pecas (custo_peca, nome_peca) values (730.93, 'Classic Beef Chili');
insert into Pecas (custo_peca, nome_peca) values (865.99, 'High-Pressure Handheld Shower Head');
insert into Pecas (custo_peca, nome_peca) values (948.33, 'Animal Paw Print Soap Dispenser');
insert into Pecas (custo_peca, nome_peca) values (511.85, 'Digital Wireless Camera');
insert into Pecas (custo_peca, nome_peca) values (485.91, 'Lemon Dill Salmon');
insert into Pecas (custo_peca, nome_peca) values (525.39, 'Pet Activity Tracker');
insert into Pecas (custo_peca, nome_peca) values (631.37, 'Coconut Macaroons');
insert into Pecas (custo_peca, nome_peca) values (610.58, 'Herb Garden Planter Box');
insert into Pecas (custo_peca, nome_peca) values (629.66, 'Maple Bacon Popcorn');
insert into Pecas (custo_peca, nome_peca) values (603.15, 'Popcorn Chicken');
insert into Pecas (custo_peca, nome_peca) values (152.76, 'Pumpkin Spice Coffee');
insert into Pecas (custo_peca, nome_peca) values (908.11, 'Body Pillow Case');
insert into Pecas (custo_peca, nome_peca) values (721.7, 'Wrist Support Brace');
insert into Pecas (custo_peca, nome_peca) values (502.79, 'Savory Snack Mix');
insert into Pecas (custo_peca, nome_peca) values (689.6, 'Leather Notebook Cover');
insert into Pecas (custo_peca, nome_peca) values (172.36, 'Elderberry Syrup');
insert into Pecas (custo_peca, nome_peca) values (587.15, 'Cinnamon Raisin Bread');
insert into Pecas (custo_peca, nome_peca) values (898.9, 'Digital Drawing Tablet');
insert into Pecas (custo_peca, nome_peca) values (366.2, 'Chipotle Black Bean Salad');
insert into Pecas (custo_peca, nome_peca) values (776.87, 'Chocolate Chip Pancake Mix');
insert into Pecas (custo_peca, nome_peca) values (933.44, 'Gardening Gloves with Claws');
insert into Pecas (custo_peca, nome_peca) values (871.02, 'Gardening Gloves');
insert into Pecas (custo_peca, nome_peca) values (904.32, 'USB Desk Fan');
insert into Pecas (custo_peca, nome_peca) values (899.13, 'Smart Plug');
insert into Pecas (custo_peca, nome_peca) values (155.8, 'Coconut Milk');
insert into Pecas (custo_peca, nome_peca) values (406.62, 'Honey Wheat Pretzels');
insert into Pecas (custo_peca, nome_peca) values (696.81, 'Ice Cream Maker');
insert into Pecas (custo_peca, nome_peca) values (181.79, 'Fried Rice');
insert into Pecas (custo_peca, nome_peca) values (962.45, 'Foot Spa Bath Massager');
insert into Pecas (custo_peca, nome_peca) values (498.41, 'Lemon Dill Salmon');
insert into Pecas (custo_peca, nome_peca) values (862.73, 'Laptop Stand');
insert into Pecas (custo_peca, nome_peca) values (459.87, 'Mayonnaise');
insert into Pecas (custo_peca, nome_peca) values (634.62, 'Plaid Flannel Shirt');
insert into Pecas (custo_peca, nome_peca) values (109.24, 'Oven-Baked Cheese Crisps');
insert into Pecas (custo_peca, nome_peca) values (280.62, 'Decorative LED Neon Sign');
insert into Pecas (custo_peca, nome_peca) values (316.94, 'French Bread');
insert into Pecas (custo_peca, nome_peca) values (715.31, 'Vanilla Bean Greek Yogurt');
insert into Pecas (custo_peca, nome_peca) values (475.08, 'Plant-Based Protein Bars');
insert into Pecas (custo_peca, nome_peca) values (589.23, 'Pet Grooming Glove');
insert into Pecas (custo_peca, nome_peca) values (929.86, 'Strawberry Fruit Spread');
insert into Pecas (custo_peca, nome_peca) values (270.54, 'Durable Hiking Boots');
insert into Pecas (custo_peca, nome_peca) values (829.01, 'Sriracha Sauce');
insert into Pecas (custo_peca, nome_peca) values (381.41, 'Smartphone Photography Tripod');
insert into Pecas (custo_peca, nome_peca) values (113.84, 'Hiking Boots');
insert into Pecas (custo_peca, nome_peca) values (302.47, 'High-Pressure Handheld Shower Head');
insert into Pecas (custo_peca, nome_peca) values (211.26, 'Honey Glazed Carrots');
insert into Pecas (custo_peca, nome_peca) values (199.49, 'Chocolate Chip Cookie Dough');
insert into Pecas (custo_peca, nome_peca) values (136.7, 'Children''s Educational Workbook');
insert into Pecas (custo_peca, nome_peca) values (641.48, 'Electric Air Pump');
insert into Pecas (custo_peca, nome_peca) values (627.0, 'Himalayan Pink Salt');
insert into Pecas (custo_peca, nome_peca) values (401.13, 'Electrolyte Water Bottle');
insert into Pecas (custo_peca, nome_peca) values (667.31, 'Bamboo Utensil Set');
insert into Pecas (custo_peca, nome_peca) values (193.17, 'Italian Meatballs');
insert into Pecas (custo_peca, nome_peca) values (646.3, 'Portable Solar Camp Shower');
insert into Pecas (custo_peca, nome_peca) values (654.32, 'Herbal Tea Variety Pack');
insert into Pecas (custo_peca, nome_peca) values (469.09, 'Fitness Smartwatch');
insert into Pecas (custo_peca, nome_peca) values (668.48, 'Portable Hammock');
insert into Pecas (custo_peca, nome_peca) values (838.79, 'Spicy Italian Sausage');
insert into Pecas (custo_peca, nome_peca) values (165.19, 'Yoga Blocks');
insert into Pecas (custo_peca, nome_peca) values (377.27, 'Spinach and Cheese Quiche');
insert into Pecas (custo_peca, nome_peca) values (671.75, 'Mango Chia Pudding');
insert into Pecas (custo_peca, nome_peca) values (545.47, 'Reusable Snack Bags');
insert into Pecas (custo_peca, nome_peca) values (370.85, 'Coffee Making Kit');
insert into Pecas (custo_peca, nome_peca) values (416.38, 'Herbal Garden Starter Kit');
insert into Pecas (custo_peca, nome_peca) values (770.26, 'Vegetable Fried Rice');
insert into Pecas (custo_peca, nome_peca) values (567.47, 'Vegetable Lasagna');
insert into Pecas (custo_peca, nome_peca) values (162.46, 'Thai Peanut Noodles');
insert into Pecas (custo_peca, nome_peca) values (409.09, 'Wall Calendar');
insert into Pecas (custo_peca, nome_peca) values (286.0, 'Vanilla Bean Greek Yogurt');
insert into Pecas (custo_peca, nome_peca) values (745.73, 'Rechargeable Electric Toothbrush');
insert into Pecas (custo_peca, nome_peca) values (468.5, 'Garden Tool Set');
insert into Pecas (custo_peca, nome_peca) values (342.84, 'Couscous');
insert into Pecas (custo_peca, nome_peca) values (626.84, 'Classic Pesto Sauce');
insert into Pecas (custo_peca, nome_peca) values (201.37, 'Organic Vanilla Bean Ice Cream');
insert into Pecas (custo_peca, nome_peca) values (471.89, 'Sweet Corn');
insert into Pecas (custo_peca, nome_peca) values (371.43, 'Whisk Set');
insert into Pecas (custo_peca, nome_peca) values (990.04, 'Puzzle');
insert into Pecas (custo_peca, nome_peca) values (500.46, 'Travel Shoe Bags Set');
insert into Pecas (custo_peca, nome_peca) values (646.65, 'Pet Caress Brush');
insert into Pecas (custo_peca, nome_peca) values (888.63, 'Mediterranean Couscous Salad');
insert into Pecas (custo_peca, nome_peca) values (396.23, 'Magic Color-Changing Mug');
insert into Pecas (custo_peca, nome_peca) values (149.88, 'Balsamic Glaze');
insert into Pecas (custo_peca, nome_peca) values (605.23, 'Automatic Pet Feeder');
insert into Pecas (custo_peca, nome_peca) values (654.86, 'Pet Food Storage Container');
insert into Pecas (custo_peca, nome_peca) values (331.36, 'Herbal Tea Set');
insert into Pecas (custo_peca, nome_peca) values (982.4, 'Salsa');
insert into Pecas (custo_peca, nome_peca) values (689.87, 'Creamy Ranch Dressing');
insert into Pecas (custo_peca, nome_peca) values (608.5, 'Relaxed Fit Henley Shirt');
insert into Pecas (custo_peca, nome_peca) values (458.89, 'Spinach Feta Wraps');
insert into Pecas (custo_peca, nome_peca) values (449.65, 'Lentil Soup (canned)');
insert into Pecas (custo_peca, nome_peca) values (802.51, 'Kids'' Craft Supplies Set');
insert into Pecas (custo_peca, nome_peca) values (511.99, 'Vegetarian Stir Fry Sauce');
insert into Pecas (custo_peca, nome_peca) values (221.05, 'Magnetic Spice Jars');
insert into Pecas (custo_peca, nome_peca) values (701.34, 'Wall-Mounted Bookshelf');
insert into Pecas (custo_peca, nome_peca) values (637.75, 'Chocolate Hazelnut Granola');
insert into Pecas (custo_peca, nome_peca) values (105.65, 'Home Office Chair');
insert into Pecas (custo_peca, nome_peca) values (346.45, 'Satin Slip Dress');
insert into Pecas (custo_peca, nome_peca) values (946.03, 'Honey mustard chicken tenders');
insert into Pecas (custo_peca, nome_peca) values (433.0, 'Honey Wheat Pretzels');
insert into Pecas (custo_peca, nome_peca) values (519.65, 'DIY Candle Making Kit');
insert into Pecas (custo_peca, nome_peca) values (648.4, 'Utility Cargo Pants');
insert into Pecas (custo_peca, nome_peca) values (666.72, 'Pasta Portion Control Measure');
insert into Pecas (custo_peca, nome_peca) values (207.5, 'Noise-Canceling Earbuds');
insert into Pecas (custo_peca, nome_peca) values (515.18, 'Sushi Roll Kit');
insert into Pecas (custo_peca, nome_peca) values (153.6, 'Fitness Tracker with Heart Rate Monitor');
insert into Pecas (custo_peca, nome_peca) values (588.59, 'Sesame Ginger Dressing');
insert into Pecas (custo_peca, nome_peca) values (377.98, 'Portable Air Compressor');
insert into Pecas (custo_peca, nome_peca) values (223.76, 'Spicy Tuna Salad');
insert into Pecas (custo_peca, nome_peca) values (331.37, 'Kitchen Scale');
insert into Pecas (custo_peca, nome_peca) values (238.32, 'Hand Mixer');
insert into Pecas (custo_peca, nome_peca) values (565.09, 'Traditional Hummus');
insert into Pecas (custo_peca, nome_peca) values (899.75, 'Electric Meat Grinder');
insert into Pecas (custo_peca, nome_peca) values (498.86, 'Smart Light Switch');
insert into Pecas (custo_peca, nome_peca) values (383.73, 'Thai Red Curry Paste');
insert into Pecas (custo_peca, nome_peca) values (223.57, 'Paprika');
insert into Pecas (custo_peca, nome_peca) values (564.14, 'Cheese Stuffed Jalapenos');
insert into Pecas (custo_peca, nome_peca) values (163.18, 'Chili Powder');
insert into Pecas (custo_peca, nome_peca) values (173.24, 'Chocolate Syrup');
insert into Pecas (custo_peca, nome_peca) values (405.11, 'Multi-Purpose Plant Care Tool');
insert into Pecas (custo_peca, nome_peca) values (804.09, 'Waffle Maker');
insert into Pecas (custo_peca, nome_peca) values (821.16, 'Plant-Based Protein Bars');
insert into Pecas (custo_peca, nome_peca) values (294.68, 'Wine Glasses');
insert into Pecas (custo_peca, nome_peca) values (184.94, 'Pet Hair Vacuum Cleaner Attachment');
insert into Pecas (custo_peca, nome_peca) values (580.48, 'Adjustable Kneeling Pad');
insert into Pecas (custo_peca, nome_peca) values (292.0, 'Peach Green Tea');
insert into Pecas (custo_peca, nome_peca) values (177.74, 'Pet Water Fountain');
insert into Pecas (custo_peca, nome_peca) values (647.31, 'Coconut Bowls Set');
insert into Pecas (custo_peca, nome_peca) values (879.15, 'Crispy Rice Treats');
insert into Pecas (custo_peca, nome_peca) values (325.63, 'Kids'' Activity Book');
insert into Pecas (custo_peca, nome_peca) values (236.97, 'Whipped Cream Cheese');
insert into Pecas (custo_peca, nome_peca) values (611.46, 'Peach Preserves');
insert into Pecas (custo_peca, nome_peca) values (207.4, 'Classic Chicken Noodle Soup');
insert into Pecas (custo_peca, nome_peca) values (408.21, 'Tuna Fish (canned)');
insert into Pecas (custo_peca, nome_peca) values (660.91, 'Reusable Coffee Filter');
insert into Pecas (custo_peca, nome_peca) values (363.32, 'Digital Stopwatch Timer');
insert into Pecas (custo_peca, nome_peca) values (649.3, 'Cheese Stuffed Jalapenos');
insert into Pecas (custo_peca, nome_peca) values (247.73, 'Mango Chunks');
insert into Pecas (custo_peca, nome_peca) values (764.97, 'Interactive Plush Toy');
insert into Pecas (custo_peca, nome_peca) values (381.32, 'Photo Album');
insert into Pecas (custo_peca, nome_peca) values (436.71, 'Banana Nut Oatmeal Cups');
insert into Pecas (custo_peca, nome_peca) values (832.41, 'Microwave Popcorn Maker');
insert into Pecas (custo_peca, nome_peca) values (287.61, 'Thai Red Curry Paste');
insert into Pecas (custo_peca, nome_peca) values (227.0, 'Nutritional Yeast');
insert into Pecas (custo_peca, nome_peca) values (367.99, 'Tactical Backpack');
insert into Pecas (custo_peca, nome_peca) values (486.44, 'Waffle Maker');
insert into Pecas (custo_peca, nome_peca) values (962.8, 'Trackpad for Laptop');
insert into Pecas (custo_peca, nome_peca) values (329.81, 'Banana Nut Muffins');
insert into Pecas (custo_peca, nome_peca) values (309.25, 'Carrot and Celery Sticks');
insert into Pecas (custo_peca, nome_peca) values (101.32, 'Non-Stick Crepe Pan');
insert into Pecas (custo_peca, nome_peca) values (538.75, 'Comfort Flats');
insert into Pecas (custo_peca, nome_peca) values (296.07, 'Hair Dryer');
insert into Pecas (custo_peca, nome_peca) values (423.67, 'Organic Coconut Flour');
insert into Pecas (custo_peca, nome_peca) values (732.92, 'Vegetarian Stir Fry Sauce');
insert into Pecas (custo_peca, nome_peca) values (409.52, 'Plant Growing Kit');
insert into Pecas (custo_peca, nome_peca) values (389.55, 'Oatmeal Raisin Cookies');
insert into Pecas (custo_peca, nome_peca) values (192.2, 'Pesto Pasta Sauce');
insert into Pecas (custo_peca, nome_peca) values (868.37, 'Silicone Cooking Utensils Set');
insert into Pecas (custo_peca, nome_peca) values (462.25, 'Summer Tank Dress');
insert into Pecas (custo_peca, nome_peca) values (947.56, 'Mango Salsa');
insert into Pecas (custo_peca, nome_peca) values (634.15, 'Fitness Balance Ball');
insert into Pecas (custo_peca, nome_peca) values (652.54, 'Chocolate Mint Protein Shake');
insert into Pecas (custo_peca, nome_peca) values (357.56, 'Skincare Fridge');
insert into Pecas (custo_peca, nome_peca) values (153.24, 'Leather Wallet');
insert into Pecas (custo_peca, nome_peca) values (924.01, 'Peanut Butter Banana Smoothie Mix');
insert into Pecas (custo_peca, nome_peca) values (240.34, 'Maple Pecan Pancake Mix');
insert into Pecas (custo_peca, nome_peca) values (632.74, 'Organic Coconut Water');
insert into Pecas (custo_peca, nome_peca) values (339.7, 'High-Speed Blender');
insert into Pecas (custo_peca, nome_peca) values (403.53, 'Beef Stew Meat');
insert into Pecas (custo_peca, nome_peca) values (958.07, 'Non-Stick Baking Sheets');
insert into Pecas (custo_peca, nome_peca) values (951.7, 'Vacuum Sealer Machine');
insert into Pecas (custo_peca, nome_peca) values (650.54, 'Fruit and Nut Medley');
insert into Pecas (custo_peca, nome_peca) values (195.11, 'Silicone Baking Molds');
insert into Pecas (custo_peca, nome_peca) values (514.07, 'Adjustable Dumbbells');
insert into Pecas (custo_peca, nome_peca) values (240.76, 'Banana Chips');
insert into Pecas (custo_peca, nome_peca) values (382.96, 'Nordic Berry Smoothie');
insert into Pecas (custo_peca, nome_peca) values (395.57, 'Teriyaki Chicken Bowl');
insert into Pecas (custo_peca, nome_peca) values (433.2, 'Coconut Oil');
insert into Pecas (custo_peca, nome_peca) values (593.94, 'Silicone Cooking Utensils Set');
insert into Pecas (custo_peca, nome_peca) values (971.43, 'Peanut Butter');
insert into Pecas (custo_peca, nome_peca) values (388.84, 'Sunglasses Case');
insert into Pecas (custo_peca, nome_peca) values (326.57, 'Garlic Herb Seasoning');
insert into Pecas (custo_peca, nome_peca) values (431.75, 'Essential White Button-Up');
insert into Pecas (custo_peca, nome_peca) values (951.04, 'Underwater Camera');
insert into Pecas (custo_peca, nome_peca) values (265.32, 'Frozen Cauliflower Rice');
insert into Pecas (custo_peca, nome_peca) values (835.52, 'Sliced Cucumbers');
insert into Pecas (custo_peca, nome_peca) values (227.28, 'Sun Protection Clothing');
insert into Pecas (custo_peca, nome_peca) values (334.18, 'Wire Shelving Unit');
insert into Pecas (custo_peca, nome_peca) values (506.55, 'Rustic Italian Bread');
insert into Pecas (custo_peca, nome_peca) values (703.59, 'Portable SSD');
insert into Pecas (custo_peca, nome_peca) values (558.64, 'Oven Thermometer');
insert into Pecas (custo_peca, nome_peca) values (296.48, 'Two-Tier Fruit Basket');
insert into Pecas (custo_peca, nome_peca) values (739.23, 'Spinach and Cheese Quiche');
insert into Pecas (custo_peca, nome_peca) values (152.69, 'Bluetooth Headphones');
insert into Pecas (custo_peca, nome_peca) values (550.98, 'Winter Insulated Jacket');
insert into Pecas (custo_peca, nome_peca) values (195.4, 'Pineapple Coconut Bars');
insert into Pecas (custo_peca, nome_peca) values (569.26, 'LED Christmas Lights');
insert into Pecas (custo_peca, nome_peca) values (557.66, 'Banana Nut Oatmeal Cups');
insert into Pecas (custo_peca, nome_peca) values (309.1, 'Mixed Berry Smoothie Pack');
insert into Pecas (custo_peca, nome_peca) values (730.94, 'Sous Vide Cooker');
insert into Pecas (custo_peca, nome_peca) values (210.24, 'Computer Monitor Stand');
insert into Pecas (custo_peca, nome_peca) values (167.38, 'LED Under Cabinet Lighting');
insert into Pecas (custo_peca, nome_peca) values (282.91, 'Portable Electric Fan');
insert into Pecas (custo_peca, nome_peca) values (864.39, 'Chili Con Carne Mix');
insert into Pecas (custo_peca, nome_peca) values (854.15, 'Organic Whole Wheat Flour');
insert into Pecas (custo_peca, nome_peca) values (671.54, 'Garlic Butter Sauce');
insert into Pecas (custo_peca, nome_peca) values (120.13, 'Coconut Cream Pie Yogurt');
insert into Pecas (custo_peca, nome_peca) values (180.26, 'Banana Chips');
insert into Pecas (custo_peca, nome_peca) values (678.14, 'Caramel Sauce');
insert into Pecas (custo_peca, nome_peca) values (109.32, 'Fitness Foam Roller');
insert into Pecas (custo_peca, nome_peca) values (943.16, 'Infrared Thermometer Gun');
insert into Pecas (custo_peca, nome_peca) values (151.16, 'Pumpkin Pie Spice');
insert into Pecas (custo_peca, nome_peca) values (653.8, 'Strawberry Fruit Spread');
insert into Pecas (custo_peca, nome_peca) values (354.92, 'Fitness Tracker Band');
insert into Pecas (custo_peca, nome_peca) values (358.14, 'Wrap Jumpsuit');
insert into Pecas (custo_peca, nome_peca) values (821.45, 'Frozen Mixed Vegetables');
insert into Pecas (custo_peca, nome_peca) values (936.0, 'Raisin Cinnamon Granola');
insert into Pecas (custo_peca, nome_peca) values (848.89, 'Peach Mango Smoothie');
insert into Pecas (custo_peca, nome_peca) values (507.31, 'Adjustable Stand for Tablets and Smartphones');
insert into Pecas (custo_peca, nome_peca) values (743.6, 'Travel Mug with Leak-Proof Lid');
insert into Pecas (custo_peca, nome_peca) values (811.09, 'Beef Stew Meat');
insert into Pecas (custo_peca, nome_peca) values (519.44, 'Cold Brew Coffee Concentrate');
insert into Pecas (custo_peca, nome_peca) values (180.86, 'Saffron Rice Mix');
insert into Pecas (custo_peca, nome_peca) values (651.37, 'Golf Polo Shirt');
insert into Pecas (custo_peca, nome_peca) values (731.21, 'Portable Hand Warmer');
insert into Pecas (custo_peca, nome_peca) values (175.27, 'Zucchini');
insert into Pecas (custo_peca, nome_peca) values (184.87, 'Almond Joy Snack Bars');
insert into Pecas (custo_peca, nome_peca) values (131.47, 'Vegan Chickpea Salad');
insert into Pecas (custo_peca, nome_peca) values (249.12, 'Frozen Berry Blend');
insert into Pecas (custo_peca, nome_peca) values (807.28, 'Cheddar & Bacon Potato Skins');
insert into Pecas (custo_peca, nome_peca) values (946.59, 'Mini Food Processor');
insert into Pecas (custo_peca, nome_peca) values (661.2, 'Ginger Turmeric Latte Mix');
insert into Pecas (custo_peca, nome_peca) values (728.19, 'High-Quality Yoga Mat');
insert into Pecas (custo_peca, nome_peca) values (387.25, 'Magnetic Curtain Tiebacks');
insert into Pecas (custo_peca, nome_peca) values (456.38, 'Electric Wax Warmer');
insert into Pecas (custo_peca, nome_peca) values (528.68, 'Silicone Ice Cube Tray');
insert into Pecas (custo_peca, nome_peca) values (977.12, 'Bamboo Toothbrush Holder');
insert into Pecas (custo_peca, nome_peca) values (270.69, 'Microfiber Cleaning Cloth Set');
insert into Pecas (custo_peca, nome_peca) values (784.16, 'Kids'' Craft Supplies Set');
insert into Pecas (custo_peca, nome_peca) values (166.5, 'Compact Shoe Rack');
insert into Pecas (custo_peca, nome_peca) values (761.67, 'Wall-Mounted Bookshelf');
insert into Pecas (custo_peca, nome_peca) values (360.01, 'Frozen Acai Purée');
insert into Pecas (custo_peca, nome_peca) values (328.96, 'Biodegradable Trash Bags');
insert into Pecas (custo_peca, nome_peca) values (911.14, 'Cinnamon Raisin Bread');
insert into Pecas (custo_peca, nome_peca) values (207.27, 'Electric Fondue Pot');
insert into Pecas (custo_peca, nome_peca) values (214.25, 'Bluetooth Tracker');
insert into Pecas (custo_peca, nome_peca) values (979.58, 'Blueberry Chia Jam');
insert into Pecas (custo_peca, nome_peca) values (433.12, 'Raspberry Vanilla Greek Yogurt');
insert into Pecas (custo_peca, nome_peca) values (102.75, 'Almond Flour Pizza Crust');
insert into Pecas (custo_peca, nome_peca) values (630.2, 'Thai Peanut Dressing');
insert into Pecas (custo_peca, nome_peca) values (945.3, 'Dark Chocolate Covered Pretzels');
insert into Pecas (custo_peca, nome_peca) values (343.89, 'Portable Campfire');
insert into Pecas (custo_peca, nome_peca) values (332.6, 'Fettuccine Alfredo Dinner Kit');
insert into Pecas (custo_peca, nome_peca) values (757.78, 'Crispy Potato Tots');
insert into Pecas (custo_peca, nome_peca) values (837.45, 'Organic Tomato Soup');
insert into Pecas (custo_peca, nome_peca) values (385.95, 'Electric Hot Pot');
insert into Pecas (custo_peca, nome_peca) values (775.83, 'Maple Almond Granola');
insert into Pecas (custo_peca, nome_peca) values (715.73, 'Hibiscus Herbal Tea');
insert into Pecas (custo_peca, nome_peca) values (682.68, 'Travel Pillow with Memory Foam');
insert into Pecas (custo_peca, nome_peca) values (320.55, 'Cinnamon Raisin Bread');
insert into Pecas (custo_peca, nome_peca) values (445.69, 'Motion Sensor Light');
insert into Pecas (custo_peca, nome_peca) values (283.82, 'Protein Pancake Mix');
insert into Pecas (custo_peca, nome_peca) values (246.74, 'Ceramic Bakeware Set');
insert into Pecas (custo_peca, nome_peca) values (580.98, 'Colorful Post-It Notes Set');
insert into Pecas (custo_peca, nome_peca) values (924.33, 'Strawberry Rhubarb Jam');
insert into Pecas (custo_peca, nome_peca) values (681.55, 'Sun-Dried Tomato Pesto');
insert into Pecas (custo_peca, nome_peca) values (525.19, 'Outdoor Adventure Kit');
insert into Pecas (custo_peca, nome_peca) values (415.36, 'Pet Travel Bowl');
insert into Pecas (custo_peca, nome_peca) values (551.85, 'Asian Salad Mix');
insert into Pecas (custo_peca, nome_peca) values (653.37, 'Water Bottle');
insert into Pecas (custo_peca, nome_peca) values (233.68, 'Organic Cucumber');
insert into Pecas (custo_peca, nome_peca) values (213.54, 'Cookbook');
insert into Pecas (custo_peca, nome_peca) values (382.57, 'Pork Chops');
insert into Pecas (custo_peca, nome_peca) values (385.42, 'Home Delivery Food Journal');
insert into Pecas (custo_peca, nome_peca) values (419.85, 'Folding Exercise Bike');
insert into Pecas (custo_peca, nome_peca) values (183.15, 'Chopping Board');
insert into Pecas (custo_peca, nome_peca) values (863.19, 'Oven-Baked Chicken Tenders');
insert into Pecas (custo_peca, nome_peca) values (958.85, 'Beard Grooming Kit');
insert into Pecas (custo_peca, nome_peca) values (390.28, 'Travel Yoga Mat');
insert into Pecas (custo_peca, nome_peca) values (120.24, 'Camera Lens Cleaning Kit');
insert into Pecas (custo_peca, nome_peca) values (133.14, 'Digital Wireless Camera');
insert into Pecas (custo_peca, nome_peca) values (979.46, 'Banana Peanut Butter Smoothie');
insert into Pecas (custo_peca, nome_peca) values (331.9, 'Sustainable Wooden Toys');
insert into Pecas (custo_peca, nome_peca) values (553.64, 'Sustainable Wooden Toys');
insert into Pecas (custo_peca, nome_peca) values (550.1, 'Adjustable Kitchen Broom Stand');
insert into Pecas (custo_peca, nome_peca) values (370.35, 'LED Desk Lamp');
insert into Pecas (custo_peca, nome_peca) values (524.87, 'Smartphone Tripod with Bluetooth Remote');
insert into Pecas (custo_peca, nome_peca) values (262.27, 'Mechanical Pencil Set');
insert into Pecas (custo_peca, nome_peca) values (681.09, 'Multi-Tool');
insert into Pecas (custo_peca, nome_peca) values (867.68, 'Self-Cleaning Cat Litter Box');
insert into Pecas (custo_peca, nome_peca) values (998.31, 'Wire Shelving Unit');
insert into Pecas (custo_peca, nome_peca) values (970.95, 'Coconut Granola');
insert into Pecas (custo_peca, nome_peca) values (739.24, 'Fruit and Nut Bars');
insert into Pecas (custo_peca, nome_peca) values (850.66, 'Classic Caesar Dressing');
insert into Pecas (custo_peca, nome_peca) values (384.46, 'Dog Waste Bag Dispenser');
insert into Pecas (custo_peca, nome_peca) values (145.03, 'Wireless Keyboard and Mouse Combo');
insert into Pecas (custo_peca, nome_peca) values (786.41, 'Colorful Post-It Notes Set');
insert into Pecas (custo_peca, nome_peca) values (555.8, 'Hydration Backpack');
insert into Pecas (custo_peca, nome_peca) values (912.01, 'Kids'' Dinosaur-Themed Lunchbox');
insert into Pecas (custo_peca, nome_peca) values (731.08, 'Frozen Mixed Vegetables');
insert into Pecas (custo_peca, nome_peca) values (896.7, 'Outdoor Inflatable Pool');
insert into Pecas (custo_peca, nome_peca) values (717.65, 'Luxury Yoga Mat');
insert into Pecas (custo_peca, nome_peca) values (664.76, 'Chocolate Mint Cookies');
insert into Pecas (custo_peca, nome_peca) values (161.76, 'Honey Roasted Chickpeas');
insert into Pecas (custo_peca, nome_peca) values (379.9, 'Beef Tacos');
insert into Pecas (custo_peca, nome_peca) values (724.39, 'Sliced Turkey Breast');
insert into Pecas (custo_peca, nome_peca) values (803.87, 'Comfort Flats');
insert into Pecas (custo_peca, nome_peca) values (877.16, 'Essential Oil Diffuser');
insert into Pecas (custo_peca, nome_peca) values (216.69, 'Organic Whole Grain Oats');
insert into Pecas (custo_peca, nome_peca) values (374.53, 'Lockable Bicycle Chain');
insert into Pecas (custo_peca, nome_peca) values (129.86, 'Car Emergency Kit');
insert into Pecas (custo_peca, nome_peca) values (829.99, 'Self-Cleaning Cat Litter Box');
insert into Pecas (custo_peca, nome_peca) values (590.47, 'Smart Plant Monitor');
insert into Pecas (custo_peca, nome_peca) values (119.31, 'Portable Pet Stroller');
insert into Pecas (custo_peca, nome_peca) values (998.41, 'Classic Cheeseburger Mix');
insert into Pecas (custo_peca, nome_peca) values (279.88, 'Butternut Squash Ravioli');
insert into Pecas (custo_peca, nome_peca) values (897.72, 'Personalized Keychain');
insert into Pecas (custo_peca, nome_peca) values (711.66, 'Garlic Parmesan Wings');
insert into Pecas (custo_peca, nome_peca) values (925.88, 'Rice Noodles');
insert into Pecas (custo_peca, nome_peca) values (373.31, 'Pasta (Linguine)');
insert into Pecas (custo_peca, nome_peca) values (736.41, 'Portable Folding Picnic Table');
insert into Pecas (custo_peca, nome_peca) values (217.53, 'Telescope');
insert into Pecas (custo_peca, nome_peca) values (273.44, 'Fishing Tackle Box');
insert into Pecas (custo_peca, nome_peca) values (145.63, 'Pork Chops');
insert into Pecas (custo_peca, nome_peca) values (460.45, 'Portable Grill Cover');
insert into Pecas (custo_peca, nome_peca) values (274.21, 'Comfort Flats');
insert into Pecas (custo_peca, nome_peca) values (422.85, 'Turkey Bacon');
insert into Pecas (custo_peca, nome_peca) values (961.6, 'Pineapple Coconut Rice Mix');
insert into Pecas (custo_peca, nome_peca) values (699.0, 'Microfiber Cleaning Cloths');
insert into Pecas (custo_peca, nome_peca) values (770.01, 'Basmati Rice');
insert into Pecas (custo_peca, nome_peca) values (986.44, 'Gingerbread House Kit');
insert into Pecas (custo_peca, nome_peca) values (710.22, 'Canvas Wall Art');
insert into Pecas (custo_peca, nome_peca) values (799.39, 'Tailored Blazer');
insert into Pecas (custo_peca, nome_peca) values (522.74, 'Karaoke Microphone');
insert into Pecas (custo_peca, nome_peca) values (823.91, 'Classic Slim Fit Shirt');
insert into Pecas (custo_peca, nome_peca) values (683.09, 'Roasted Sweet Corn');
insert into Pecas (custo_peca, nome_peca) values (402.87, 'Electric Hot Water Dispenser');
insert into Pecas (custo_peca, nome_peca) values (708.15, 'Garlic Butter Sauce');
insert into Pecas (custo_peca, nome_peca) values (242.78, 'Cheese Stuffed Jalapenos');
insert into Pecas (custo_peca, nome_peca) values (701.34, 'Spicy BBQ Sauce');
insert into Pecas (custo_peca, nome_peca) values (146.5, 'Whole Wheat Pasta');
insert into Pecas (custo_peca, nome_peca) values (735.25, 'LED Strip Light Kit');
insert into Pecas (custo_peca, nome_peca) values (576.66, 'Black Bean Soup');
insert into Pecas (custo_peca, nome_peca) values (983.48, 'Vegan Protein Powder');
insert into Pecas (custo_peca, nome_peca) values (286.99, 'Balsamic Vinegar');
insert into Pecas (custo_peca, nome_peca) values (724.18, 'Microwave Popcorn Maker');
insert into Pecas (custo_peca, nome_peca) values (613.19, 'Chilli Lime Corn on the Cob');
insert into Pecas (custo_peca, nome_peca) values (192.97, 'Chiffon Blouse');
insert into Pecas (custo_peca, nome_peca) values (612.54, 'Frozen Acai Purée');
insert into Pecas (custo_peca, nome_peca) values (413.0, 'Camera Lens Cleaning Kit');
insert into Pecas (custo_peca, nome_peca) values (489.58, 'Bluetooth Headphones');
insert into Pecas (custo_peca, nome_peca) values (816.93, 'Electric Wine Opener');
insert into Pecas (custo_peca, nome_peca) values (156.62, 'Camping Chair with Cooler');
insert into Pecas (custo_peca, nome_peca) values (958.67, '3D Night Light');
insert into Pecas (custo_peca, nome_peca) values (268.17, 'Vanilla Bean Greek Yogurt');
insert into Pecas (custo_peca, nome_peca) values (765.46, 'Chocolate Syrup');
insert into Pecas (custo_peca, nome_peca) values (664.04, 'Pumpkin Spice Granola');
insert into Pecas (custo_peca, nome_peca) values (555.88, 'Classic Minestrone Soup');
insert into Pecas (custo_peca, nome_peca) values (467.36, 'Spicy Snack Mix');
insert into Pecas (custo_peca, nome_peca) values (550.87, 'Adjustable Garden Rake');
insert into Pecas (custo_peca, nome_peca) values (324.06, 'Low-Fat Yogurt');
insert into Pecas (custo_peca, nome_peca) values (927.83, 'Dog Training Clicker');
insert into Pecas (custo_peca, nome_peca) values (922.24, 'Sliced Avocado');
insert into Pecas (custo_peca, nome_peca) values (935.84, 'Cinnamon Raisin Bagels');
insert into Pecas (custo_peca, nome_peca) values (229.74, 'Blueberry Oatmeal Cups');
insert into Pecas (custo_peca, nome_peca) values (697.24, 'Solar Power Bank');
insert into Pecas (custo_peca, nome_peca) values (482.74, 'Honey Sriracha Chicken Bites');
insert into Pecas (custo_peca, nome_peca) values (757.89, 'Blender Bottle');
insert into Pecas (custo_peca, nome_peca) values (510.26, 'Kids Tablet');
insert into Pecas (custo_peca, nome_peca) values (230.59, 'Gluten-Free Biscuits');
insert into Pecas (custo_peca, nome_peca) values (712.7, 'Fitness Foam Roller');
insert into Pecas (custo_peca, nome_peca) values (446.9, 'Smoked Gouda Cheese');
insert into Pecas (custo_peca, nome_peca) values (117.81, 'Almond Butter Granola Bars');
insert into Pecas (custo_peca, nome_peca) values (766.02, 'Caramelized Onion Dip Mix');
insert into Pecas (custo_peca, nome_peca) values (516.98, 'Hydration Backpack');
insert into Pecas (custo_peca, nome_peca) values (955.81, 'Savory Pumpkin Soup');
insert into Pecas (custo_peca, nome_peca) values (649.18, 'Slim Wallet');
insert into Pecas (custo_peca, nome_peca) values (777.22, 'Camping Chair');
insert into Pecas (custo_peca, nome_peca) values (219.48, 'Wireless Security Camera');
insert into Pecas (custo_peca, nome_peca) values (893.92, 'Shower Curtain Hooks');
insert into Pecas (custo_peca, nome_peca) values (852.85, 'Self-Inflating Camping Mattress');
insert into Pecas (custo_peca, nome_peca) values (326.84, 'Beef Chili');
insert into Pecas (custo_peca, nome_peca) values (243.69, 'Compact Shoe Rack');
insert into Pecas (custo_peca, nome_peca) values (255.91, 'Chocolate Chip Muffins');
insert into Pecas (custo_peca, nome_peca) values (738.49, 'Kids'' Craft Supplies Set');
insert into Pecas (custo_peca, nome_peca) values (288.97, 'Children''s Gardening Set');
insert into Pecas (custo_peca, nome_peca) values (705.34, 'Portable Hammock');
insert into Pecas (custo_peca, nome_peca) values (607.65, 'Garlic Herb Cream Cheese');
insert into Pecas (custo_peca, nome_peca) values (931.03, 'Black Bean Spaghetti');
insert into Pecas (custo_peca, nome_peca) values (209.32, 'Herbal Tea Set');
insert into Pecas (custo_peca, nome_peca) values (445.78, 'Coconut Oil');
insert into Pecas (custo_peca, nome_peca) values (826.34, 'Banana Nut Oatmeal Cups');
insert into Pecas (custo_peca, nome_peca) values (897.65, 'Kids'' Craft Supplies Set');
insert into Pecas (custo_peca, nome_peca) values (707.62, 'Travel Shoe Bags Set');
insert into Pecas (custo_peca, nome_peca) values (441.12, 'Smoky BBQ Jackfruit');
insert into Pecas (custo_peca, nome_peca) values (748.46, 'Lentil Soup');
insert into Pecas (custo_peca, nome_peca) values (362.43, 'Multi-Functional Rice Cooker');
insert into Pecas (custo_peca, nome_peca) values (141.65, 'BBQ Lentil Chips');
insert into Pecas (custo_peca, nome_peca) values (287.81, 'Solar Charger');
insert into Pecas (custo_peca, nome_peca) values (971.7, 'Avocado Lime Dressing');
insert into Pecas (custo_peca, nome_peca) values (264.61, 'Vegan Mac & Cheese');
insert into Pecas (custo_peca, nome_peca) values (419.29, 'Travel Mug with Leak-Proof Lid');
insert into Pecas (custo_peca, nome_peca) values (159.26, 'Habanero Hot Sauce');
insert into Pecas (custo_peca, nome_peca) values (625.18, 'Classic Cheeseburger Mix');
insert into Pecas (custo_peca, nome_peca) values (550.05, 'Cacao Powder');
insert into Pecas (custo_peca, nome_peca) values (944.35, 'Cucumber');
insert into Pecas (custo_peca, nome_peca) values (241.3, 'Compact Folding Table');
insert into Pecas (custo_peca, nome_peca) values (837.95, 'Garden Kneeler and Seat');
insert into Pecas (custo_peca, nome_peca) values (328.12, 'Basil Pesto Pasta');
insert into Pecas (custo_peca, nome_peca) values (881.14, 'Oven-Baked Parmesan Zucchini');
insert into Pecas (custo_peca, nome_peca) values (801.86, 'Cordless Electric Screwdriver');
insert into Pecas (custo_peca, nome_peca) values (765.75, 'Mixed Berry Smoothie Pack');
insert into Pecas (custo_peca, nome_peca) values (526.47, 'Spinach Pizza Rolls');
insert into Pecas (custo_peca, nome_peca) values (930.75, 'Thai Peanut Dressing');
insert into Pecas (custo_peca, nome_peca) values (861.17, 'Granola Bars');
insert into Pecas (custo_peca, nome_peca) values (368.41, 'Classic Cheeseburger Mix');
insert into Pecas (custo_peca, nome_peca) values (407.9, 'Suction Cup Hooks');
insert into Pecas (custo_peca, nome_peca) values (975.99, 'Electric Food Steamer');
insert into Pecas (custo_peca, nome_peca) values (534.74, 'Fruit & Nut Trail Mix');
insert into Pecas (custo_peca, nome_peca) values (582.65, 'Air Fryer Oven');
insert into Pecas (custo_peca, nome_peca) values (425.49, 'Biodegradable Trash Bags');
insert into Pecas (custo_peca, nome_peca) values (376.06, 'Wooden Toy Train Set');
insert into Pecas (custo_peca, nome_peca) values (971.71, 'Portable Ice Maker');
insert into Pecas (custo_peca, nome_peca) values (492.79, 'Chili Lime Seasoning');
insert into Pecas (custo_peca, nome_peca) values (698.64, 'Smartwatch');
insert into Pecas (custo_peca, nome_peca) values (582.54, 'Wireless Mouse');
insert into Pecas (custo_peca, nome_peca) values (954.21, 'Pet Food Storage Container');
insert into Pecas (custo_peca, nome_peca) values (869.23, 'Vegan Mac & Cheese');
insert into Pecas (custo_peca, nome_peca) values (884.47, 'Ice Pack');
insert into Pecas (custo_peca, nome_peca) values (469.76, 'Mango Chutney');
insert into Pecas (custo_peca, nome_peca) values (206.79, 'Yoga Blocks');
insert into Pecas (custo_peca, nome_peca) values (666.95, 'Warm Wool Sweater');
insert into Pecas (custo_peca, nome_peca) values (902.14, 'Compact Electric Kettle');
insert into Pecas (custo_peca, nome_peca) values (874.95, 'Kettle BBQ Grill');
insert into Pecas (custo_peca, nome_peca) values (145.82, 'Rice Noodles');
insert into Pecas (custo_peca, nome_peca) values (917.62, 'Pistachio Ice Cream');
insert into Pecas (custo_peca, nome_peca) values (981.8, 'Biodegradable Phone Case');
insert into Pecas (custo_peca, nome_peca) values (441.27, 'Vegan Taco Seasoning');
insert into Pecas (custo_peca, nome_peca) values (207.4, 'Ground Turkey');
insert into Pecas (custo_peca, nome_peca) values (301.6, 'Floral Wrap Top');
insert into Pecas (custo_peca, nome_peca) values (405.25, 'Screen Cleaning Kit');
insert into Pecas (custo_peca, nome_peca) values (272.88, 'Portable Projector');
insert into Pecas (custo_peca, nome_peca) values (838.38, 'Organic Coconut Yogurt');
insert into Pecas (custo_peca, nome_peca) values (811.01, 'Cinnamon Sugar Popcorn');
insert into Pecas (custo_peca, nome_peca) values (187.73, 'Nut Butter Cups');
insert into Pecas (custo_peca, nome_peca) values (955.54, 'Classic Pesto Sauce');
insert into Pecas (custo_peca, nome_peca) values (941.4, 'Watercolor Paint Set');
insert into Pecas (custo_peca, nome_peca) values (602.08, 'Luxury Yoga Mat');
insert into Pecas (custo_peca, nome_peca) values (292.54, 'Survival Gear Kit');
insert into Pecas (custo_peca, nome_peca) values (844.62, 'Pest Control Traps');
insert into Pecas (custo_peca, nome_peca) values (885.46, 'Portable Massage Table');
insert into Pecas (custo_peca, nome_peca) values (773.8, 'Non-Stick Grill Mat');
insert into Pecas (custo_peca, nome_peca) values (408.28, 'Teriyaki Stir-Fry Sauce');
insert into Pecas (custo_peca, nome_peca) values (173.53, 'Lemon Dill Chicken Skewers');
insert into Pecas (custo_peca, nome_peca) values (386.8, 'Stainless Steel Grater');
insert into Pecas (custo_peca, nome_peca) values (686.66, 'Brown Rice');
insert into Pecas (custo_peca, nome_peca) values (342.28, 'Fruit and Nut Medley');
insert into Pecas (custo_peca, nome_peca) values (508.45, 'Interactive Robot Toy');
insert into Pecas (custo_peca, nome_peca) values (844.14, 'Foldable Yoga Mat');
insert into Pecas (custo_peca, nome_peca) values (988.53, 'Sriracha Hot Chili Sauce');
insert into Pecas (custo_peca, nome_peca) values (716.78, 'Magnetic Puzzle Board');
insert into Pecas (custo_peca, nome_peca) values (937.38, 'Folding Backpack Chair');
insert into Pecas (custo_peca, nome_peca) values (989.82, 'Folding Pocket Knife');
insert into Pecas (custo_peca, nome_peca) values (316.37, 'Organic Spinach');
insert into Pecas (custo_peca, nome_peca) values (754.44, 'Pesto Pasta Salad');
insert into Pecas (custo_peca, nome_peca) values (135.04, 'Body Wash');
insert into Pecas (custo_peca, nome_peca) values (774.9, 'Sunglasses');
insert into Pecas (custo_peca, nome_peca) values (928.13, 'Organic Italian Seasoning');
insert into Pecas (custo_peca, nome_peca) values (161.91, 'Electric Heat Pad');
insert into Pecas (custo_peca, nome_peca) values (370.86, 'Raspberry Tart');
insert into Pecas (custo_peca, nome_peca) values (782.9, 'Vegan Chickpea Salad');
insert into Pecas (custo_peca, nome_peca) values (831.86, 'Chunky Knit Sweater');
insert into Pecas (custo_peca, nome_peca) values (216.34, 'Customizable Name Puzzle');
insert into Pecas (custo_peca, nome_peca) values (907.63, 'Trail Mix (Deluxe)');
insert into Pecas (custo_peca, nome_peca) values (455.12, 'LED Strip Lights Kit');
insert into Pecas (custo_peca, nome_peca) values (217.57, 'Coconut Curry Sauce');
insert into Pecas (custo_peca, nome_peca) values (384.57, 'Glass Food Containers');
insert into Pecas (custo_peca, nome_peca) values (279.45, 'Andouille Sausage');
insert into Pecas (custo_peca, nome_peca) values (696.23, 'Whole Wheat Pasta');
insert into Pecas (custo_peca, nome_peca) values (276.94, 'Body Wash');
insert into Pecas (custo_peca, nome_peca) values (750.84, 'Peach Mango Smoothie');
insert into Pecas (custo_peca, nome_peca) values (581.75, 'Ice Pack');
insert into Pecas (custo_peca, nome_peca) values (676.47, 'Sesame Noodles');
insert into Pecas (custo_peca, nome_peca) values (210.95, 'Pumpkin Spice Creamer');
insert into Pecas (custo_peca, nome_peca) values (202.1, 'Sweet Potato Chips');
insert into Pecas (custo_peca, nome_peca) values (716.8, 'Handcrafted Wooden Jewelry Box');
insert into Pecas (custo_peca, nome_peca) values (590.17, 'Handheld Shower Head');
insert into Pecas (custo_peca, nome_peca) values (113.96, 'LED Desk Lamp with USB Charging');
insert into Pecas (custo_peca, nome_peca) values (764.5, 'Air Fryer Oven');
insert into Pecas (custo_peca, nome_peca) values (176.83, 'Spinach Artichoke Dip');
insert into Pecas (custo_peca, nome_peca) values (683.94, 'Scented Candle Set');
insert into Pecas (custo_peca, nome_peca) values (740.7, 'Fresh Cilantro');
insert into Pecas (custo_peca, nome_peca) values (912.81, 'Elegant Lace Dress');
insert into Pecas (custo_peca, nome_peca) values (489.92, 'Outdoor Adventure Backpack');
insert into Pecas (custo_peca, nome_peca) values (908.43, 'Peanut Butter Chocolate Chip Bars');
insert into Pecas (custo_peca, nome_peca) values (451.9, 'Saffron Rice Mix');
insert into Pecas (custo_peca, nome_peca) values (769.74, 'Habanero Hot Sauce');
insert into Pecas (custo_peca, nome_peca) values (604.26, 'Almond Butter Crunch Bar');
insert into Pecas (custo_peca, nome_peca) values (272.93, 'Desk Lamp with USB Port');
insert into Pecas (custo_peca, nome_peca) values (250.56, 'Butternut Squash Soup');
insert into Pecas (custo_peca, nome_peca) values (610.53, 'Cocktail Shaker and Mixing Glass Set');
insert into Pecas (custo_peca, nome_peca) values (843.34, 'Low-Fat Cottage Cheese');
insert into Pecas (custo_peca, nome_peca) values (833.02, 'Sour Cream');
insert into Pecas (custo_peca, nome_peca) values (367.59, 'Italian Sausage and Peppers');
insert into Pecas (custo_peca, nome_peca) values (780.22, 'Self-Watering Planters');
insert into Pecas (custo_peca, nome_peca) values (474.16, 'Frozen Spinach');
insert into Pecas (custo_peca, nome_peca) values (250.94, 'Smart Home Hub');
insert into Pecas (custo_peca, nome_peca) values (775.76, 'Graphic Print Leggings');
insert into Pecas (custo_peca, nome_peca) values (202.57, 'Electric Rice Cooker with Steamer');
insert into Pecas (custo_peca, nome_peca) values (585.05, 'Smoked Gouda Cheese');
insert into Pecas (custo_peca, nome_peca) values (870.78, 'Garden Vegetable Chips');
insert into Pecas (custo_peca, nome_peca) values (778.15, 'Organic Cereal Bars');
insert into Pecas (custo_peca, nome_peca) values (775.89, 'Bluetooth Sleep Headphones');
insert into Pecas (custo_peca, nome_peca) values (993.19, 'Smartphone Projector Kit');
insert into Pecas (custo_peca, nome_peca) values (698.21, 'Foot Massager Machine');
insert into Pecas (custo_peca, nome_peca) values (745.46, 'Wall Calendar');
insert into Pecas (custo_peca, nome_peca) values (145.58, 'Vegetable Stir-Fry Sauce');
insert into Pecas (custo_peca, nome_peca) values (460.8, 'Classic Cheeseburger Mix');
insert into Pecas (custo_peca, nome_peca) values (288.09, 'Wooden Toy Train Set');
insert into Pecas (custo_peca, nome_peca) values (198.32, 'Nature Explorer Lens Kit');
insert into Pecas (custo_peca, nome_peca) values (889.04, 'Herb-Infused Olive Oil');
insert into Pecas (custo_peca, nome_peca) values (973.9, 'Set of Decorative Storage Bins');
insert into Pecas (custo_peca, nome_peca) values (547.36, 'Electric Nail File Kit');
insert into Pecas (custo_peca, nome_peca) values (393.18, 'Digital Food Thermometer');
insert into Pecas (custo_peca, nome_peca) values (894.01, 'Air Mattress');
insert into Pecas (custo_peca, nome_peca) values (335.69, 'Inspirational Wall Art');
insert into Pecas (custo_peca, nome_peca) values (272.27, 'Sweet Cherry Tomatoes');
insert into Pecas (custo_peca, nome_peca) values (422.33, 'Pet Travel Bed');
insert into Pecas (custo_peca, nome_peca) values (836.49, 'Pet First Aid Kit');
insert into Pecas (custo_peca, nome_peca) values (949.03, 'Multifunctional Pocket Tool');
insert into Pecas (custo_peca, nome_peca) values (629.83, 'Fishing Rod');
insert into Pecas (custo_peca, nome_peca) values (239.19, 'Outdoor Picnic Blanket');
insert into Pecas (custo_peca, nome_peca) values (432.94, 'Silicone Baking Mat');
insert into Pecas (custo_peca, nome_peca) values (559.18, 'Pineapple Chunks (canned)');
insert into Pecas (custo_peca, nome_peca) values (199.91, 'Sketchbook');
insert into Pecas (custo_peca, nome_peca) values (694.08, 'Travel Shoe Bags Set');
insert into Pecas (custo_peca, nome_peca) values (731.94, 'Tuna Fish (canned)');
insert into Pecas (custo_peca, nome_peca) values (287.41, 'Cordless Water Flosser');
insert into Pecas (custo_peca, nome_peca) values (846.77, 'Plant-Based Meal Prep Containers');
insert into Pecas (custo_peca, nome_peca) values (793.77, 'Dog Collar');
insert into Pecas (custo_peca, nome_peca) values (843.93, 'Wireless Charging Pad');
insert into Pecas (custo_peca, nome_peca) values (511.61, 'Kids'' Crafting Station');
insert into Pecas (custo_peca, nome_peca) values (960.45, 'Woven Storage Baskets');
insert into Pecas (custo_peca, nome_peca) values (493.57, 'Reusable Silicone Food Storage Bags');
insert into Pecas (custo_peca, nome_peca) values (404.38, 'Honey Roasted Almonds');
insert into Pecas (custo_peca, nome_peca) values (687.71, 'Running Shorts');
insert into Pecas (custo_peca, nome_peca) values (814.01, 'Pet First Aid Kit');
insert into Pecas (custo_peca, nome_peca) values (986.22, 'Mini Indoor Herb Garden Kit');
insert into Pecas (custo_peca, nome_peca) values (550.35, 'Butternut Squash Soup');
insert into Pecas (custo_peca, nome_peca) values (730.5, 'Sliced Cucumbers');
insert into Pecas (custo_peca, nome_peca) values (761.06, 'Scented Soy Candles');
insert into Pecas (custo_peca, nome_peca) values (719.36, 'Personalized Pet ID Tags');
insert into Pecas (custo_peca, nome_peca) values (619.59, 'Herb Seasoned Rice');
insert into Pecas (custo_peca, nome_peca) values (254.76, 'Inspirational Wall Art');
insert into Pecas (custo_peca, nome_peca) values (876.31, 'Kitchen Knife Sharpening System');
insert into Pecas (custo_peca, nome_peca) values (649.84, 'Pumpkin Spice Creamer');
insert into Pecas (custo_peca, nome_peca) values (613.44, 'Eggs (dozen)');
insert into Pecas (custo_peca, nome_peca) values (185.01, 'Ceramic Knife Set');
insert into Pecas (custo_peca, nome_peca) values (328.29, 'Classic Pumps');
insert into Pecas (custo_peca, nome_peca) values (488.23, 'Coconut Curry Sauce');
insert into Pecas (custo_peca, nome_peca) values (122.4, 'Wireless Charger');
insert into Pecas (custo_peca, nome_peca) values (493.07, 'Honeycrisp Apple Chips');
insert into Pecas (custo_peca, nome_peca) values (788.73, 'Foam Roller for Muscle Recovery');
insert into Pecas (custo_peca, nome_peca) values (190.56, 'Bluetooth Headphones');
insert into Pecas (custo_peca, nome_peca) values (237.2, 'Diced Tomatoes (canned)');
insert into Pecas (custo_peca, nome_peca) values (193.34, 'Cinnamon Sugar Mix');
insert into Pecas (custo_peca, nome_peca) values (305.51, 'Two-Tier Fruit Basket');
insert into Pecas (custo_peca, nome_peca) values (608.82, 'Vegetable Stir Fry Mix');
insert into Pecas (custo_peca, nome_peca) values (822.27, 'Basil-infused Olive Oil');
insert into Pecas (custo_peca, nome_peca) values (727.5, 'Stuffed Bell Peppers');
insert into Pecas (custo_peca, nome_peca) values (158.65, 'Wall-Mounted Wine Rack');
insert into Pecas (custo_peca, nome_peca) values (281.22, 'Mediterranean Olives');
insert into Pecas (custo_peca, nome_peca) values (407.65, 'Weighted Blanket for Adults');
insert into Pecas (custo_peca, nome_peca) values (965.38, 'Coffee Subscription Service');
insert into Pecas (custo_peca, nome_peca) values (896.23, 'Lemon Lime Sparkling Water');
insert into Pecas (custo_peca, nome_peca) values (534.11, 'Beef Jerky');
insert into Pecas (custo_peca, nome_peca) values (326.88, 'Frozen Salmon Filets');
insert into Pecas (custo_peca, nome_peca) values (183.56, 'Radish Chips');
insert into Pecas (custo_peca, nome_peca) values (691.96, 'Chopping Board');
insert into Pecas (custo_peca, nome_peca) values (226.57, 'Portable Electric Fan');
insert into Pecas (custo_peca, nome_peca) values (241.61, 'Overnight Duffle Bag');
insert into Pecas (custo_peca, nome_peca) values (721.3, 'Children''s Musical Instrument Set');
insert into Pecas (custo_peca, nome_peca) values (945.57, 'Sparkling Blood Orange Soda');
insert into Pecas (custo_peca, nome_peca) values (759.61, 'Guitar Tuner');
insert into Pecas (custo_peca, nome_peca) values (212.98, 'Handmade Leather Journal');
insert into Pecas (custo_peca, nome_peca) values (233.67, 'Caramelized Onion Dip Mix');
insert into Pecas (custo_peca, nome_peca) values (133.56, 'Wireless Printer');
insert into Pecas (custo_peca, nome_peca) values (157.43, 'Rain Jacket');
insert into Pecas (custo_peca, nome_peca) values (837.15, 'Winter Insulated Jacket');
insert into Pecas (custo_peca, nome_peca) values (306.4, 'Glass Tea Pot');
insert into Pecas (custo_peca, nome_peca) values (924.41, 'Herb-Infused Olive Oil');
insert into Pecas (custo_peca, nome_peca) values (340.33, 'Adjustable Dog Harness');
insert into Pecas (custo_peca, nome_peca) values (895.53, 'Antique Style Clock');
insert into Pecas (custo_peca, nome_peca) values (996.78, 'Savory Mushroom Risotto');
insert into Pecas (custo_peca, nome_peca) values (934.51, 'Homestyle Beef Stew');
insert into Pecas (custo_peca, nome_peca) values (162.06, 'Italian Sausage Links');
insert into Pecas (custo_peca, nome_peca) values (992.07, 'Buffalo Cauliflower Wings');
insert into Pecas (custo_peca, nome_peca) values (178.37, 'Sparkling Blood Orange Soda');
insert into Pecas (custo_peca, nome_peca) values (500.92, 'Honey Sesame Chicken Mix');
insert into Pecas (custo_peca, nome_peca) values (401.72, 'Over-Ear Headphones');
insert into Pecas (custo_peca, nome_peca) values (744.09, 'Jasmine Rice');
insert into Pecas (custo_peca, nome_peca) values (636.24, 'Wooden Kitchen Utensil Set');
insert into Pecas (custo_peca, nome_peca) values (804.1, 'Coconut Almond Granola');
insert into Pecas (custo_peca, nome_peca) values (346.06, 'Collapsible Water Bottle');
insert into Pecas (custo_peca, nome_peca) values (235.22, 'Wireless Gaming Headset');
insert into Pecas (custo_peca, nome_peca) values (126.42, 'Peanut Butter Filled Pretzels');
insert into Pecas (custo_peca, nome_peca) values (855.7, 'Tea Infuser');
insert into Pecas (custo_peca, nome_peca) values (595.53, 'Drone');
insert into Pecas (custo_peca, nome_peca) values (826.98, 'Trackpad for Laptop');
insert into Pecas (custo_peca, nome_peca) values (553.91, 'Car Vacuum Cleaner');
insert into Pecas (custo_peca, nome_peca) values (532.88, 'Thai Green Curry Paste');
insert into Pecas (custo_peca, nome_peca) values (285.39, 'Chocolate Protein Powder');
insert into Pecas (custo_peca, nome_peca) values (604.94, 'High-Waisted Skirt');
insert into Pecas (custo_peca, nome_peca) values (497.72, 'Fitness Activity Journal');
insert into Pecas (custo_peca, nome_peca) values (648.01, 'Chino Shorts');
insert into Pecas (custo_peca, nome_peca) values (570.2, 'Peach Yogurt');
insert into Pecas (custo_peca, nome_peca) values (308.19, 'Dark Chocolate Covered Pretzels');
insert into Pecas (custo_peca, nome_peca) values (238.36, 'Spicy Chicken Wings');
insert into Pecas (custo_peca, nome_peca) values (877.44, 'Pumpkin Waffles');
insert into Pecas (custo_peca, nome_peca) values (559.13, 'Car Seat Organizer');
insert into Pecas (custo_peca, nome_peca) values (716.81, 'Mediterranean Flatbread');
insert into Pecas (custo_peca, nome_peca) values (415.54, 'Coconut Cream Pie Yogurt');
insert into Pecas (custo_peca, nome_peca) values (999.27, 'Scented Soy Candles');
insert into Pecas (custo_peca, nome_peca) values (847.54, 'Sesame Seeds');
insert into Pecas (custo_peca, nome_peca) values (425.92, 'Microfiber Cleaning Cloths');
insert into Pecas (custo_peca, nome_peca) values (798.85, 'Baked Falafel Balls');
insert into Pecas (custo_peca, nome_peca) values (905.03, 'Aeropress Coffee Maker');
insert into Pecas (custo_peca, nome_peca) values (515.48, 'USB Desk Fan');
insert into Pecas (custo_peca, nome_peca) values (128.18, 'Adjustable Kneeling Pad');
insert into Pecas (custo_peca, nome_peca) values (369.75, 'Portable Water Filter');
insert into Pecas (custo_peca, nome_peca) values (875.52, 'Leather Biker Jacket');
insert into Pecas (custo_peca, nome_peca) values (968.53, 'Organic Whole Grain Oats');
insert into Pecas (custo_peca, nome_peca) values (874.47, 'Creamy Ranch Dressing');
insert into Pecas (custo_peca, nome_peca) values (845.81, 'Chicken Parmesan Dinner Kit');
insert into Pecas (custo_peca, nome_peca) values (402.54, 'Sriracha Honey Glaze');
insert into Pecas (custo_peca, nome_peca) values (541.15, 'Comfortable Bed Pillow');
insert into Pecas (custo_peca, nome_peca) values (801.72, 'Pasta (Linguine)');
insert into Pecas (custo_peca, nome_peca) values (820.19, 'Set of Silicone Baking Molds');
insert into Pecas (custo_peca, nome_peca) values (922.42, 'Silicone Wine Glasses');
insert into Pecas (custo_peca, nome_peca) values (509.59, 'Digital Meat Thermometer');
insert into Pecas (custo_peca, nome_peca) values (872.23, 'Canvas High-Top Sneakers');
insert into Pecas (custo_peca, nome_peca) values (431.83, 'Peanut Butter Protein Balls');
insert into Pecas (custo_peca, nome_peca) values (513.1, 'Organic Brown Rice Cakes');
insert into Pecas (custo_peca, nome_peca) values (454.06, 'Electric Stool Heater');
insert into Pecas (custo_peca, nome_peca) values (948.99, 'Vegan Tacos');
insert into Pecas (custo_peca, nome_peca) values (752.7, 'Relaxed Fit Henley Shirt');
insert into Pecas (custo_peca, nome_peca) values (331.57, 'Sculpting Kit');
insert into Pecas (custo_peca, nome_peca) values (164.64, 'Chickpea Salad Deluxe');
insert into Pecas (custo_peca, nome_peca) values (688.76, 'Laptop Sleeve');
insert into Pecas (custo_peca, nome_peca) values (921.23, 'Cotton Sweatpants');
insert into Pecas (custo_peca, nome_peca) values (396.83, 'Compact Umbrella');
insert into Pecas (custo_peca, nome_peca) values (963.35, 'Tomato Sauce');
insert into Pecas (custo_peca, nome_peca) values (512.06, 'Tomato Paste');
insert into Pecas (custo_peca, nome_peca) values (708.23, 'Herb Seasoned Couscous');
insert into Pecas (custo_peca, nome_peca) values (944.12, 'Jennifer''s Amazing Lip Balm Kit');
insert into Pecas (custo_peca, nome_peca) values (156.02, 'Peach Green Tea');
insert into Pecas (custo_peca, nome_peca) values (637.28, 'Magnetic Whiteboard');
insert into Pecas (custo_peca, nome_peca) values (370.47, 'Cranberry Lime Sparkling Water');
insert into Pecas (custo_peca, nome_peca) values (611.18, 'Whole Chicken');
insert into Pecas (custo_peca, nome_peca) values (450.49, 'Camping Chair with Cooler');
insert into Pecas (custo_peca, nome_peca) values (134.47, 'Chocolate Chip Cookie Dough');
insert into Pecas (custo_peca, nome_peca) values (286.94, 'Blue Denim Jeans');
insert into Pecas (custo_peca, nome_peca) values (942.79, 'Classic White T-Shirt');
insert into Pecas (custo_peca, nome_peca) values (531.95, 'Deluxe First Aid Kit');
insert into Pecas (custo_peca, nome_peca) values (249.05, 'Dried Cranberries');
insert into Pecas (custo_peca, nome_peca) values (420.23, 'Automatic Pet Feeder');
insert into Pecas (custo_peca, nome_peca) values (161.85, 'Collapsible Camping Cup');
insert into Pecas (custo_peca, nome_peca) values (312.73, 'Electric Fondue Pot');
insert into Pecas (custo_peca, nome_peca) values (964.73, 'Vanilla Ice Cream');
insert into Pecas (custo_peca, nome_peca) values (797.16, 'Poppy Seed Dressing');
insert into Pecas (custo_peca, nome_peca) values (321.14, 'Wooden Toy Train Set');
insert into Pecas (custo_peca, nome_peca) values (324.57, 'Mayonnaise');
insert into Pecas (custo_peca, nome_peca) values (569.95, 'Bike Helmet');
insert into Pecas (custo_peca, nome_peca) values (454.91, 'Car Windshield Sun Shade');
insert into Pecas (custo_peca, nome_peca) values (517.15, 'Folding Backpack Chair');
insert into Pecas (custo_peca, nome_peca) values (371.71, 'Travel Shoe Bags Set');
insert into Pecas (custo_peca, nome_peca) values (599.04, 'Tofu');
insert into Pecas (custo_peca, nome_peca) values (649.16, 'LED Disco Ball Light');
insert into Pecas (custo_peca, nome_peca) values (190.41, 'Portable UV Sterilizer');
insert into Pecas (custo_peca, nome_peca) values (942.05, 'Set of Silicone Cooking Utensils');
insert into Pecas (custo_peca, nome_peca) values (995.75, 'Whole Grain Cereal');
insert into Pecas (custo_peca, nome_peca) values (833.77, 'Plant Pot Drip Trays');
insert into Pecas (custo_peca, nome_peca) values (579.41, 'Tahini');
insert into Pecas (custo_peca, nome_peca) values (353.38, 'Stainless Steel Grater');
insert into Pecas (custo_peca, nome_peca) values (971.48, 'Essential White Button-Up');
insert into Pecas (custo_peca, nome_peca) values (920.37, 'Magnetic Puzzle Board');
insert into Pecas (custo_peca, nome_peca) values (833.2, 'Pumpkin Pancake Mix');
insert into Pecas (custo_peca, nome_peca) values (273.57, 'Italian Breadsticks');
insert into Pecas (custo_peca, nome_peca) values (328.87, 'Dill Pickle Chips');
insert into Pecas (custo_peca, nome_peca) values (928.31, 'Air Fryer Oven');
insert into Pecas (custo_peca, nome_peca) values (679.57, 'Chocolate Peanut Butter Cups');
insert into Pecas (custo_peca, nome_peca) values (619.59, 'Customizable Name Puzzle');
insert into Pecas (custo_peca, nome_peca) values (402.43, 'Oven Mitts');
insert into Pecas (custo_peca, nome_peca) values (480.27, 'Frozen Mixed Berries');
insert into Pecas (custo_peca, nome_peca) values (220.94, 'Nutty Quinoa Salad');
insert into Pecas (custo_peca, nome_peca) values (470.45, 'Black Bean Spaghetti');
insert into Pecas (custo_peca, nome_peca) values (481.53, 'Collapsible Water Bottle');
insert into Pecas (custo_peca, nome_peca) values (551.45, 'Pumpkin Spice Pancake Mix');
insert into Pecas (custo_peca, nome_peca) values (540.03, 'USB Flash Drive');
insert into Pecas (custo_peca, nome_peca) values (956.14, 'Plant-Based Protein Bars');
insert into Pecas (custo_peca, nome_peca) values (415.82, 'Chicken Breasts');
insert into Pecas (custo_peca, nome_peca) values (536.91, 'Mechanical Keyboard');
insert into Pecas (custo_peca, nome_peca) values (577.54, 'Cordless Electric Screwdriver');
insert into Pecas (custo_peca, nome_peca) values (702.81, 'Falafel Mix');
insert into Pecas (custo_peca, nome_peca) values (554.69, 'Whole Wheat Pita Bread');
insert into Pecas (custo_peca, nome_peca) values (373.15, 'Hiking Boots');
insert into Pecas (custo_peca, nome_peca) values (217.29, 'Savory Trail Mix');
insert into Pecas (custo_peca, nome_peca) values (976.74, 'Winter Knit Beanie');
insert into Pecas (custo_peca, nome_peca) values (806.83, 'Chino Shorts');
insert into Pecas (custo_peca, nome_peca) values (398.9, 'Instant Pot');
insert into Pecas (custo_peca, nome_peca) values (367.2, 'Potato Wedge Seasoning');
insert into Pecas (custo_peca, nome_peca) values (883.18, 'Tailored Blazer');
insert into Pecas (custo_peca, nome_peca) values (766.51, 'Stainless Steel Water Pitcher');
insert into Pecas (custo_peca, nome_peca) values (946.67, 'Smartphone Gimbal');
insert into Pecas (custo_peca, nome_peca) values (493.84, 'Maple Almond Butter');
insert into Pecas (custo_peca, nome_peca) values (716.96, 'Cabbage Slaw Mix');
insert into Pecas (custo_peca, nome_peca) values (468.98, 'Dish Rack');
insert into Pecas (custo_peca, nome_peca) values (268.05, 'Weighted Jump Rope with Counter');
insert into Pecas (custo_peca, nome_peca) values (863.87, 'Coconut Milk');
insert into Pecas (custo_peca, nome_peca) values (515.84, 'Honey BBQ Ribs');
insert into Pecas (custo_peca, nome_peca) values (149.8, 'Digital Kitchen Timer');
insert into Pecas (custo_peca, nome_peca) values (407.72, 'Sweet Potato Mash');
insert into Pecas (custo_peca, nome_peca) values (977.9, 'Camping Lantern');
insert into Pecas (custo_peca, nome_peca) values (653.48, 'Ginger Turmeric Tea');
insert into Pecas (custo_peca, nome_peca) values (579.38, 'Scented Candles');
insert into Pecas (custo_peca, nome_peca) values (580.1, 'Digital Stopwatch Timer');
insert into Pecas (custo_peca, nome_peca) values (317.65, 'Baking Soda');
insert into Pecas (custo_peca, nome_peca) values (560.12, 'Pumpkin Spice Coffee');
insert into Pecas (custo_peca, nome_peca) values (303.7, 'Stuffed Bell Peppers');
insert into Pecas (custo_peca, nome_peca) values (177.69, 'Spinach and Cheese Stuffed Shells');
insert into Pecas (custo_peca, nome_peca) values (931.65, 'Pomegranate Juice');
insert into Pecas (custo_peca, nome_peca) values (106.07, 'Coffee Subscription Service');
insert into Pecas (custo_peca, nome_peca) values (384.22, 'Adjustable Garden Rake');
insert into Pecas (custo_peca, nome_peca) values (105.45, 'Durable Hiking Boots');
insert into Pecas (custo_peca, nome_peca) values (287.09, 'Nutritional Yeast');
insert into Pecas (custo_peca, nome_peca) values (665.49, 'DIY Lip Balm Kit');
insert into Pecas (custo_peca, nome_peca) values (125.15, 'Microfiber Cleaning Cloth Set');
insert into Pecas (custo_peca, nome_peca) values (719.78, 'Eco-Friendly Yoga Blocks');
insert into Pecas (custo_peca, nome_peca) values (970.34, 'Chocolate Fudge Ice Cream');
insert into Pecas (custo_peca, nome_peca) values (100.11, 'Chic Jumpsuit');
insert into Pecas (custo_peca, nome_peca) values (339.97, 'Cold Brew Coffee Maker');
insert into Pecas (custo_peca, nome_peca) values (732.51, 'Suction Cup Hooks');
insert into Pecas (custo_peca, nome_peca) values (720.34, 'Luxury Yoga Mat');
insert into Pecas (custo_peca, nome_peca) values (685.7, 'Solar Power Bank');
insert into Pecas (custo_peca, nome_peca) values (981.94, 'Multifunctional Baby Bottle Warmer');
insert into Pecas (custo_peca, nome_peca) values (244.72, 'Chocolate Mint Thins');
insert into Pecas (custo_peca, nome_peca) values (184.83, 'Teriyaki Sauce');
insert into Pecas (custo_peca, nome_peca) values (697.46, 'Mini Projector');
insert into Pecas (custo_peca, nome_peca) values (912.0, 'Outdoor Mosquito Repellent Lantern');
insert into Pecas (custo_peca, nome_peca) values (578.96, 'Strawberry Banana Smoothie Pack');
insert into Pecas (custo_peca, nome_peca) values (695.51, 'Sweet Potatoes (organic)');
insert into Pecas (custo_peca, nome_peca) values (921.12, 'Hibiscus Tea Bags');
insert into Pecas (custo_peca, nome_peca) values (148.71, 'Spinach and Feta Stuffed Chicken Breast');
insert into Pecas (custo_peca, nome_peca) values (214.07, 'Almond Crunch Granola Bars');
insert into Pecas (custo_peca, nome_peca) values (630.14, 'Walnut Halves');
insert into Pecas (custo_peca, nome_peca) values (626.57, 'Spicy Hummus');
insert into Pecas (custo_peca, nome_peca) values (770.2, 'Organic Coconut Flour');
insert into Pecas (custo_peca, nome_peca) values (280.17, 'Chic Jumpsuit');
insert into Pecas (custo_peca, nome_peca) values (585.48, 'Roasted Garlic Aioli');
insert into Pecas (custo_peca, nome_peca) values (243.58, 'Kids'' Trampoline');
insert into Pecas (custo_peca, nome_peca) values (475.97, 'Mini Indoor Hydroponic Garden');
insert into Pecas (custo_peca, nome_peca) values (720.04, 'Terry Cloth Robe');
insert into Pecas (custo_peca, nome_peca) values (627.84, 'Rustic Italian Bread');
insert into Pecas (custo_peca, nome_peca) values (557.6, 'Thai Peanut Noodles');
insert into Pecas (custo_peca, nome_peca) values (842.15, 'Portable Bluetooth Headphones');
insert into Pecas (custo_peca, nome_peca) values (576.85, 'Maple Almond Butter');
insert into Pecas (custo_peca, nome_peca) values (680.6, 'Lemon Herb Grilled Chicken');
insert into Pecas (custo_peca, nome_peca) values (198.51, 'Almond Flour Pizza Crust');
insert into Pecas (custo_peca, nome_peca) values (190.37, 'Dried Apricots');
insert into Pecas (custo_peca, nome_peca) values (488.04, 'Children''s Gardening Set');
insert into Pecas (custo_peca, nome_peca) values (412.38, 'Coconut Milk');
insert into Pecas (custo_peca, nome_peca) values (975.78, 'Smoked Gouda Cheese');
insert into Pecas (custo_peca, nome_peca) values (359.73, 'Mango Chutney');
insert into Pecas (custo_peca, nome_peca) values (309.98, 'Flavored Rice Cakes');
insert into Pecas (custo_peca, nome_peca) values (807.29, 'Wooden Puzzle Game');
insert into Pecas (custo_peca, nome_peca) values (710.81, 'Kids'' Trampoline');
insert into Pecas (custo_peca, nome_peca) values (233.89, 'Tomatillo Salsa');
insert into Pecas (custo_peca, nome_peca) values (456.67, 'Honeycrisp Apple Chips');
insert into Pecas (custo_peca, nome_peca) values (108.88, 'Pasta Salad Kit');
insert into Pecas (custo_peca, nome_peca) values (289.61, 'Aeropress Coffee Maker');
insert into Pecas (custo_peca, nome_peca) values (256.45, 'Garden Vegetable Chips');
insert into Pecas (custo_peca, nome_peca) values (140.18, 'Eco-Friendly Yoga Blocks');
insert into Pecas (custo_peca, nome_peca) values (166.07, 'Smart Doorbell');
insert into Pecas (custo_peca, nome_peca) values (346.02, 'Blackberry Jam');
insert into Pecas (custo_peca, nome_peca) values (599.25, 'Adjustable Bar Stools');
insert into Pecas (custo_peca, nome_peca) values (795.09, 'Memory Card');
insert into Pecas (custo_peca, nome_peca) values (642.39, 'Peach Fruit Cups');
insert into Pecas (custo_peca, nome_peca) values (894.33, 'Thai Red Curry Paste');
insert into Pecas (custo_peca, nome_peca) values (912.83, 'Spinach and Feta Wraps');
insert into Pecas (custo_peca, nome_peca) values (942.79, 'Cat Scratching Post with Toys');
insert into Pecas (custo_peca, nome_peca) values (872.95, 'Biodegradable Trash Bags');
insert into Pecas (custo_peca, nome_peca) values (327.65, 'Honey mustard chicken tenders');
insert into Pecas (custo_peca, nome_peca) values (691.84, 'Basil-infused Olive Oil');
insert into Pecas (custo_peca, nome_peca) values (208.05, 'Electric Toothbrush Holder');
insert into Pecas (custo_peca, nome_peca) values (363.63, 'Vintage Button-Down Shirt');
insert into Pecas (custo_peca, nome_peca) values (506.86, 'Gingerbread House Kit');
insert into Pecas (custo_peca, nome_peca) values (780.86, 'Cajun Seasoning');
insert into Pecas (custo_peca, nome_peca) values (741.34, 'Smart LED Desk Lamp');
insert into Pecas (custo_peca, nome_peca) values (845.42, 'Gardening Gloves with Claws');
insert into Pecas (custo_peca, nome_peca) values (418.5, 'Organic Whole Wheat Flour');
insert into Pecas (custo_peca, nome_peca) values (813.2, 'Oven-Baked Sweet Potato Fries');
insert into Pecas (custo_peca, nome_peca) values (135.33, 'Reusable Food Storage Bags');
insert into Pecas (custo_peca, nome_peca) values (973.46, 'Home Karaoke System');
insert into Pecas (custo_peca, nome_peca) values (746.31, 'Garden Tool Set');
insert into Pecas (custo_peca, nome_peca) values (467.33, 'Gaming Mousepad');
insert into Pecas (custo_peca, nome_peca) values (149.73, 'Crispy Kale Chips');
insert into Pecas (custo_peca, nome_peca) values (462.14, 'Organic Green Lentils');
insert into Pecas (custo_peca, nome_peca) values (572.26, 'Beef Enchilada Casserole');
insert into Pecas (custo_peca, nome_peca) values (158.25, 'Fire Roasted Salsa');
insert into Pecas (custo_peca, nome_peca) values (804.94, 'Ginger Turmeric Shots');
insert into Pecas (custo_peca, nome_peca) values (635.3, 'Raspberry Tart');
insert into Pecas (custo_peca, nome_peca) values (350.16, 'Wire Shelving Unit');
insert into Pecas (custo_peca, nome_peca) values (209.9, 'Animal Paw Print Soap Dispenser');
insert into Pecas (custo_peca, nome_peca) values (727.78, 'Butternut Squash Ravioli');
insert into Pecas (custo_peca, nome_peca) values (583.11, 'Sketchbook');
insert into Pecas (custo_peca, nome_peca) values (505.47, 'Drone');
insert into Pecas (custo_peca, nome_peca) values (261.88, 'Almond Flour');
insert into Pecas (custo_peca, nome_peca) values (829.09, 'Set of Gardening Gloves with Claws');
insert into Pecas (custo_peca, nome_peca) values (526.05, 'Mini Hand Gesture Drone');
insert into Pecas (custo_peca, nome_peca) values (466.69, 'Spaghetti Sauce');
insert into Pecas (custo_peca, nome_peca) values (430.24, 'Vegetable Korma');
insert into Pecas (custo_peca, nome_peca) values (836.16, 'Spinach Artichoke Dip');
insert into Pecas (custo_peca, nome_peca) values (372.99, 'Travel Luggage Scale');
insert into Pecas (custo_peca, nome_peca) values (554.28, 'Almond Flour Bread Mix');
insert into Pecas (custo_peca, nome_peca) values (880.34, 'Kids'' Art Supplies Kit');
insert into Pecas (custo_peca, nome_peca) values (736.3, 'USB Flash Drive');
insert into Pecas (custo_peca, nome_peca) values (817.32, 'Paint By Numbers Kit');
insert into Pecas (custo_peca, nome_peca) values (675.42, 'Ginger Tea');
insert into Pecas (custo_peca, nome_peca) values (444.76, 'Children''s Science Experiment Lab Kit');
insert into Pecas (custo_peca, nome_peca) values (252.08, 'Chocolate Almond Milk');
insert into Pecas (custo_peca, nome_peca) values (321.38, 'Educational STEM Kit');
insert into Pecas (custo_peca, nome_peca) values (888.53, 'Maple Almond Granola');
insert into Pecas (custo_peca, nome_peca) values (626.31, 'Drone');
insert into Pecas (custo_peca, nome_peca) values (633.37, 'Nutty Trail Mix');
insert into Pecas (custo_peca, nome_peca) values (884.68, 'Sporty Cap');
insert into Pecas (custo_peca, nome_peca) values (675.41, 'Spicy Roasted Nuts');
insert into Pecas (custo_peca, nome_peca) values (572.89, 'Lemon Herb Quinoa');
insert into Pecas (custo_peca, nome_peca) values (478.27, 'Eco-Friendly Cleaning Cloths');
insert into Pecas (custo_peca, nome_peca) values (703.52, 'Digital Drawing Tablet');
insert into Pecas (custo_peca, nome_peca) values (325.16, 'Black Bean Soup');
insert into Pecas (custo_peca, nome_peca) values (479.94, 'Ice Cream Scoop');
insert into Pecas (custo_peca, nome_peca) values (856.48, 'Hair Dryer');
insert into Pecas (custo_peca, nome_peca) values (629.2, 'Plaid Flannel Shirt');
insert into Pecas (custo_peca, nome_peca) values (174.58, 'Pleated Midi Dress');
insert into Pecas (custo_peca, nome_peca) values (464.97, 'Dried Cranberries');
insert into Pecas (custo_peca, nome_peca) values (423.03, 'Garden Hose');
insert into Pecas (custo_peca, nome_peca) values (533.41, 'Electronic Drum Kit');
insert into Pecas (custo_peca, nome_peca) values (356.11, 'Blackberry Compote');
insert into Pecas (custo_peca, nome_peca) values (990.25, 'Plaid Flannel Shirt');
insert into Pecas (custo_peca, nome_peca) values (710.56, 'Turmeric Ginger Tea');
insert into Pecas (custo_peca, nome_peca) values (109.0, 'Organic Tomato Soup');
insert into Pecas (custo_peca, nome_peca) values (749.71, 'Leather Crossbody Bag');
insert into Pecas (custo_peca, nome_peca) values (660.57, 'Bluetooth Shower Speaker');
insert into Pecas (custo_peca, nome_peca) values (110.05, 'Tea Infuser');
insert into Pecas (custo_peca, nome_peca) values (139.16, 'Rechargeable Hand Warmer');
insert into Pecas (custo_peca, nome_peca) values (155.74, 'Frozen Mixed Vegetables');
insert into Pecas (custo_peca, nome_peca) values (408.95, 'Athletic Compression Tights');
insert into Pecas (custo_peca, nome_peca) values (682.76, 'Self-Watering Planters');
insert into Pecas (custo_peca, nome_peca) values (616.76, 'Miso Soup Mix');
insert into Pecas (custo_peca, nome_peca) values (267.72, 'Herbal Tea Set');
insert into Pecas (custo_peca, nome_peca) values (185.34, 'Leather Wallet');
insert into Pecas (custo_peca, nome_peca) values (730.97, 'Fresh Strawberries');
insert into Pecas (custo_peca, nome_peca) values (100.59, 'Digital Stopwatch Timer');
insert into Pecas (custo_peca, nome_peca) values (818.2, 'Digital Meat Thermometer');
insert into Pecas (custo_peca, nome_peca) values (483.55, 'DIY Lip Balm Making Kit');
insert into Pecas (custo_peca, nome_peca) values (689.51, 'Pet Hair Remover');
insert into Pecas (custo_peca, nome_peca) values (295.46, 'Sliced Bread');
insert into Pecas (custo_peca, nome_peca) values (631.41, 'Miso Soup Starter');
insert into Pecas (custo_peca, nome_peca) values (954.43, 'Butternut Squash Soup');
insert into Pecas (custo_peca, nome_peca) values (440.62, 'Patterned Knit Scarf');
insert into Pecas (custo_peca, nome_peca) values (804.78, 'Sour Cream');
insert into Pecas (custo_peca, nome_peca) values (431.79, 'Honey Wheat Pretzels');
insert into Pecas (custo_peca, nome_peca) values (316.62, 'Blackberry Compote');
insert into Pecas (custo_peca, nome_peca) values (485.37, 'Cacao Powder');
insert into Pecas (custo_peca, nome_peca) values (593.74, 'Almond Milk');
insert into Pecas (custo_peca, nome_peca) values (511.15, 'Cilantro Lime Rice');
insert into Pecas (custo_peca, nome_peca) values (447.23, 'Balsamic Glazed Brussels Sprouts');
insert into Pecas (custo_peca, nome_peca) values (487.94, 'Kitchen Knife Sharpening System');
insert into Pecas (custo_peca, nome_peca) values (256.57, 'Fitness Tracker Band');
insert into Pecas (custo_peca, nome_peca) values (708.23, 'Maple Almond Butter');
insert into Pecas (custo_peca, nome_peca) values (551.83, 'Digital Photo Frame');
insert into Pecas (custo_peca, nome_peca) values (407.28, 'Lemon Lime Sparkling Water');
insert into Pecas (custo_peca, nome_peca) values (756.46, 'Canvas Tote Bag');
insert into Pecas (custo_peca, nome_peca) values (105.58, 'Oven-Baked Potato Chips');
insert into Pecas (custo_peca, nome_peca) values (836.49, 'Pasta Portion Control Measure');
insert into Pecas (custo_peca, nome_peca) values (436.29, 'Caramelized Onion Dip');
insert into Pecas (custo_peca, nome_peca) values (803.13, 'Spinach Artichoke Dip');
insert into Pecas (custo_peca, nome_peca) values (444.9, 'Nutritional Yeast');
insert into Pecas (custo_peca, nome_peca) values (823.27, 'Tortilla Chips');
insert into Pecas (custo_peca, nome_peca) values (602.46, 'LED Table Lamp');
insert into Pecas (custo_peca, nome_peca) values (231.84, 'Sweet Potato Chips');
insert into Pecas (custo_peca, nome_peca) values (913.74, 'Kids'' Gardening Tools Set');
insert into Pecas (custo_peca, nome_peca) values (227.56, 'Vegan chocolate chip cookies');
insert into Pecas (custo_peca, nome_peca) values (272.87, 'Personal Blender with Travel Cup');
insert into Pecas (custo_peca, nome_peca) values (792.42, 'Desk Lamp with USB Port');
insert into Pecas (custo_peca, nome_peca) values (467.42, 'Ribbed Knit Dress');
insert into Pecas (custo_peca, nome_peca) values (275.85, 'Pepperoni Pizza Roll-Ups');
insert into Pecas (custo_peca, nome_peca) values (790.71, 'Portable Campfire');
insert into Pecas (custo_peca, nome_peca) values (363.6, 'Electric Hot Pot');
insert into Pecas (custo_peca, nome_peca) values (899.94, 'Pumpkin Spice Pancake Mix');
insert into Pecas (custo_peca, nome_peca) values (305.4, 'Cordless Water Flosser');
insert into Pecas (custo_peca, nome_peca) values (372.94, 'Infrared Thermometer');
insert into Pecas (custo_peca, nome_peca) values (291.82, 'Fitness Tracker Watch');
insert into Pecas (custo_peca, nome_peca) values (676.09, 'Leather Wallet');
insert into Pecas (custo_peca, nome_peca) values (266.53, 'Cat Scratching Post with Toys');
insert into Pecas (custo_peca, nome_peca) values (275.86, 'Running Shorts');
insert into Pecas (custo_peca, nome_peca) values (737.12, 'Tomato Basil Pasta Sauce');
insert into Pecas (custo_peca, nome_peca) values (950.17, 'Kids'' Art Supplies Kit');
insert into Pecas (custo_peca, nome_peca) values (290.81, 'Sweet Chili Sauce');
insert into Pecas (custo_peca, nome_peca) values (939.55, 'Trail Mix (Deluxe)');
insert into Pecas (custo_peca, nome_peca) values (672.29, 'Infrared Space Heater');
insert into Pecas (custo_peca, nome_peca) values (230.18, 'Pet Grooming Glove');
insert into Pecas (custo_peca, nome_peca) values (234.11, 'Pork Tenderloin');
insert into Pecas (custo_peca, nome_peca) values (133.46, 'Sweet Potato & Kale Hash');
insert into Pecas (custo_peca, nome_peca) values (639.66, 'Sliced Bell Peppers');
insert into Pecas (custo_peca, nome_peca) values (683.74, 'Elegant Maxi Skirt');
insert into Pecas (custo_peca, nome_peca) values (386.97, 'Whisk Set');
insert into Pecas (custo_peca, nome_peca) values (144.54, 'Ripped Boyfriend Jeans');
insert into Pecas (custo_peca, nome_peca) values (549.91, 'Wall Art Stickers');
insert into Pecas (custo_peca, nome_peca) values (546.79, 'Durable Hiking Boots');
insert into Pecas (custo_peca, nome_peca) values (434.3, 'Chocolate Mint Cookies');
insert into Pecas (custo_peca, nome_peca) values (202.14, 'Sliced Avocado');
insert into Pecas (custo_peca, nome_peca) values (792.17, 'Foldable Yoga Mat Carry Bag');
insert into Pecas (custo_peca, nome_peca) values (318.39, 'Organic Coconut Sugar');
insert into Pecas (custo_peca, nome_peca) values (279.72, 'Mayonnaise');
insert into Pecas (custo_peca, nome_peca) values (790.55, 'Almond Flour');
insert into Pecas (custo_peca, nome_peca) values (241.46, 'Nutritional Yeast');
insert into Pecas (custo_peca, nome_peca) values (631.04, 'Recipe Book Stand');
insert into Pecas (custo_peca, nome_peca) values (660.66, 'Almond Joy Bars');
insert into Pecas (custo_peca, nome_peca) values (214.04, 'Weighted Blanket');
insert into Pecas (custo_peca, nome_peca) values (415.08, 'Basil Lemonade');
insert into Pecas (custo_peca, nome_peca) values (595.74, 'Wireless Earbuds Case');
insert into Pecas (custo_peca, nome_peca) values (752.34, 'Ceramic Non-Stick Frying Pan');
insert into Pecas (custo_peca, nome_peca) values (639.57, 'Chiffon Blouse');
insert into Pecas (custo_peca, nome_peca) values (361.86, 'Wireless Car Charger');
insert into Pecas (custo_peca, nome_peca) values (777.34, 'Vegan Alfredo Sauce');
insert into Pecas (custo_peca, nome_peca) values (806.47, 'Ultraviolet Phone Sanitizer');
insert into Pecas (custo_peca, nome_peca) values (844.95, 'Falafel Mix');
insert into Pecas (custo_peca, nome_peca) values (381.35, 'Peanut Butter');
insert into Pecas (custo_peca, nome_peca) values (555.7, 'Wild Rice Pilaf');
insert into Pecas (custo_peca, nome_peca) values (595.35, 'Creamy Garlic Mashed Potatoes');
insert into Pecas (custo_peca, nome_peca) values (618.42, 'Basil-infused Olive Oil');
insert into Pecas (custo_peca, nome_peca) values (286.63, 'Roasted Vegetable Medley');
insert into Pecas (custo_peca, nome_peca) values (970.09, 'Car Windshield Sun Shade');
insert into Pecas (custo_peca, nome_peca) values (207.84, 'Organic Apples');
insert into Pecas (custo_peca, nome_peca) values (936.7, 'Electric Bike');
insert into Pecas (custo_peca, nome_peca) values (944.71, 'Animal Paw Print Soap Dispenser');
insert into Pecas (custo_peca, nome_peca) values (775.13, 'Rolling Cooler');
insert into Pecas (custo_peca, nome_peca) values (539.29, 'Karaoke Microphone');
insert into Pecas (custo_peca, nome_peca) values (800.13, 'Travel Pillow');
insert into Pecas (custo_peca, nome_peca) values (166.63, 'Kids'' Dinosaur-Themed Lunchbox');
insert into Pecas (custo_peca, nome_peca) values (764.44, 'Honey mustard chicken tenders');
insert into Pecas (custo_peca, nome_peca) values (559.01, 'Pumpkin Spice Muffins');
insert into Pecas (custo_peca, nome_peca) values (655.06, 'Ice Cube Tray with Lid');
insert into Pecas (custo_peca, nome_peca) values (300.94, 'Blueberry Oatmeal Cups');
insert into Pecas (custo_peca, nome_peca) values (453.41, 'Noise-Canceling Earbuds');
insert into Pecas (custo_peca, nome_peca) values (541.99, 'Casual Cropped Sweater');
insert into Pecas (custo_peca, nome_peca) values (752.9, 'Stainless Steel Travel Mug');
insert into Pecas (custo_peca, nome_peca) values (517.86, 'Low-Fat Cottage Cheese');
insert into Pecas (custo_peca, nome_peca) values (428.13, 'Juice Extractor');
insert into Pecas (custo_peca, nome_peca) values (427.73, 'Classic Black Trousers');
insert into Pecas (custo_peca, nome_peca) values (710.97, 'Car Seat Organizer');
insert into Pecas (custo_peca, nome_peca) values (667.35, 'Kombucha Drink');
insert into Pecas (custo_peca, nome_peca) values (523.61, 'Essential Oil Roller Bottles');
insert into Pecas (custo_peca, nome_peca) values (953.41, 'Lentil Vegetable Curry');
insert into Pecas (custo_peca, nome_peca) values (449.64, 'Travel Yoga Mat');
insert into Pecas (custo_peca, nome_peca) values (800.81, 'Car Windshield Sun Shade');
insert into Pecas (custo_peca, nome_peca) values (524.27, 'Vegetarian Stuffed Peppers');
insert into Pecas (custo_peca, nome_peca) values (112.01, 'Vanilla Pudding Mix');
insert into Pecas (custo_peca, nome_peca) values (509.74, 'Vegetable Stir Fry Mix');
insert into Pecas (custo_peca, nome_peca) values (529.94, 'Zucchini Noodles');
insert into Pecas (custo_peca, nome_peca) values (260.62, 'Chocolate Hazelnut Granola');
insert into Pecas (custo_peca, nome_peca) values (892.05, 'Peanut Butter Banana Smoothie');
insert into Pecas (custo_peca, nome_peca) values (720.15, 'Low-Fat Cottage Cheese');
insert into Pecas (custo_peca, nome_peca) values (450.15, 'Compact Shoe Rack');
insert into Pecas (custo_peca, nome_peca) values (471.8, 'Organic Brown Sugar');
insert into Pecas (custo_peca, nome_peca) values (355.91, 'Compact Folding Table');
insert into Pecas (custo_peca, nome_peca) values (671.34, 'Garam Masala Spice Blend');
insert into Pecas (custo_peca, nome_peca) values (543.08, 'Digital Food Thermometer');
insert into Pecas (custo_peca, nome_peca) values (448.69, 'Roasted Garlic Pasta Sauce');
insert into Pecas (custo_peca, nome_peca) values (169.63, 'Mediterranean Olives');
insert into Pecas (custo_peca, nome_peca) values (530.61, 'Kettle BBQ Grill');
insert into Pecas (custo_peca, nome_peca) values (462.77, 'Handmade Leather Journal');
insert into Pecas (custo_peca, nome_peca) values (350.04, 'Pineapple Coconut Rice Mix');
insert into Pecas (custo_peca, nome_peca) values (255.11, 'Portable Pet Stroller');
insert into Pecas (custo_peca, nome_peca) values (163.37, 'Magnetic Screen Door');
insert into Pecas (custo_peca, nome_peca) values (156.04, 'Electric Food Steamer');
insert into Pecas (custo_peca, nome_peca) values (978.86, 'Gardening Gloves');
insert into Pecas (custo_peca, nome_peca) values (471.55, 'Plant-Based Protein Bars');
