insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$553.44', 'Leather Biker Jacket');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$605.17', 'Classic Cheesecake Mix');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$302.80', 'Banana Peanut Butter Smoothie');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$829.23', 'Children''s Art Set');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$943.38', 'Rice Cakes');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$657.29', 'Smart Home Security Camera');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$729.45', 'Eco-Friendly Notepad');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$681.48', 'Chia Seeds');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$727.07', 'Infrared Thermometer');
insert into Peças (id_Peças, custo_peça, nome_peça) values (null, '$927.16', 'Faux Leather Leggings');
