INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('ABC-1234', 1, 'Electra', 'Crimson');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('DEF-4567', 2, 'Ram Wagon B150', 'Turquoise');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('MNO-7890', 3, 'Element', 'Khaki');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('GHI-3456', 10, 'Murano', 'Orange');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('PQR-0123', 4, 'Probe', 'Maroon');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('QWE-9012', 5, 'Golf III', 'Khaki');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('STU-0123', 6, 'SLK-Class', 'Crimson');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('RST-2345', 7, 'Land Cruiser', 'Goldenrod');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('VWX-4567', 8, 'S-Class', 'Orange');
INSERT INTO Veiculo (placa_veiculo, idCliente, modelo, cor) VALUES ('XYZ-5678', 9, 'Mustang', 'Red');