insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('SIT-9923', 1, 'Scirocco', 'Indigo');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('LIU-1329', 2, 'Coupe Quattro', 'Khaki');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('VSH-9526', 3, 'Corvette', 'Yellow');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('GTJ-2978', 4, 'S4', 'Orange');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('ZWR-1823', 5, '550', 'Red');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('UMG-3397', 6, 'Lancer Evolution', 'Maroon');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('NBX-6617', 7, 'Grand Prix', 'Maroon');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('COF-2732', 8, 'F250', 'Blue');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('YYM-6778', 9, 'Ram Van 2500', 'Goldenrod');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('RWN-0113', 10, 'Grand Voyager', 'Mauv');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('XSD-2253', 11, 'Envoy', 'Purple');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('VCG-1261', 12, 'Daewoo Magnus', 'Orange');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('JSS-9023', 13, 'Countach', 'Indigo');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('BHJ-5684', 14, 'S-Type', 'Crimson');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('MHI-5416', 15, 'XG300', 'Yellow');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('QFA-7964', 16, 'Baja', 'Khaki');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('IYV-5191', 17, 'Armada', 'Puce');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('KHE-6931', 18, 'Ranger', 'Fuscia');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('TES-4888', 19, 'R32', 'Goldenrod');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('SNX-2492', 20, 'Pajero', 'Turquoise');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('JNE-2741', 21, 'R8', 'Pink');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('BUF-0724', 22, '1500', 'Indigo');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('MXB-4993', 23, 'Mazda6 5-Door', 'Mauv');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('MYB-5211', 24, 'IS', 'Purple');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('BWV-1328', 25, '280ZX', 'Khaki');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('SCJ-2183', 26, 'LS', 'Teal');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('AEV-2290', 27, 'Mustang', 'Turquoise');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('CZR-2683', 28, 'Continental Mark VII', 'Puce');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('GZZ-5574', 29, 'M5', 'Puce');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('IRQ-5020', 30, 'Paseo', 'Crimson');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('VSY-9972', 31, 'Trooper', 'Red');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('IUV-3523', 32, 'Camaro', 'Yellow');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('EJE-6034', 33, 'Seville', 'Maroon');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('PIL-4188', 34, 'A8', 'Teal');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('JQG-0752', 35, 'Topaz', 'Crimson');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('GSU-6495', 36, 'Camry', 'Teal');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('EAY-6817', 37, 'C-Class', 'Red');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('YES-8397', 38, 'Supra', 'Pink');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('NRP-9904', 39, 'Concorde', 'Violet');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('EET-4563', 40, '745', 'Turquoise');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('VUX-8291', 41, 'RAV4', 'Blue');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('LIL-1180', 42, 'Sentra', 'Purple');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('BLA-0922', 43, 'RVR', 'Goldenrod');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('CNF-3234', 44, 'A6', 'Yellow');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('RCY-9284', 45, 'Montero', 'Yellow');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('PQN-8706', 46, 'Seville', 'Red');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('FMV-4188', 47, 'XC70', 'Purple');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('MGM-6967', 48, 'Blazer', 'Fuscia');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('WEA-5360', 49, 'XF', 'Aquamarine');
insert into Veiculo (placa_veiculo, id_Cliente, modelo, cor) values ('ZQG-0614', 50, 'LeSabre', 'Aquamarine');
